/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The supported ANC modes in Aspen
 */
public enum AncMode {
  /**
   *  The ANC mode is undefined; either the headset hasn't reported<br>
   *                              it, or the headset failed to report it properly. 
   */
  UNDEFINED,
  /**
   *  The ANC is off. 
   */
  OFF,
  /**
   *  The ANC is on. 
   */
  ON,
  /**
   *  The ANC is in transparency mode. 
   */
  TRANSPARENCY;

  public final int swigValue() {
    return swigValue;
  }

  public static AncMode swigToEnum(int swigValue) {
    AncMode[] swigValues = AncMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AncMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AncMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AncMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AncMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AncMode(AncMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

