/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;
import androidx.annotation.Nullable;
/**
 * The AspenManager class<br>
 * <br>
 * This is the main class of the Aspen library. It contains the<br>
 * available service interfaces, version, et cetera.
 */
public class AspenManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AspenManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AspenManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AspenManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private IVirtualDeviceServiceCallbacks vCallbackReference;

  protected static void init(String license_key, Environment env, String storage_path) {
    AspenJNI.AspenManager_init__SWIG_0(license_key, Environment.getCPtr(env), env, storage_path);
  }

  protected static void init(String license_key, Environment env, String storage_path, String config_blob) {
    AspenJNI.AspenManager_init__SWIG_1(license_key, Environment.getCPtr(env), env, storage_path, config_blob);
  }

  protected static AspenManager getInstance() {
    long cPtr = AspenJNI.AspenManager_getInstance();
    return (cPtr == 0) ? null : new AspenManager(cPtr, false);
  }

  /**
   * Getter for the <a href="#IProfileService">IProfileService</a>.<br>
   * <br>
   * Gets an interface to the profile service, which can be used to manage<br>
   * profiles.<br>
   * <br>
   * @return A pointer to the profile service.
   */
  public IProfileService getProfileService() {
    long cPtr = AspenJNI.AspenManager_getProfileService(swigCPtr, this);
    return (cPtr == 0) ? null : new IProfileService(cPtr, true);
  }

  /**
   * Get the Aspen version.<br>
   * <br>
   * @return A string containing the Aspen version.
   */
  public String getVersion() {
    return AspenJNI.AspenManager_getVersion(swigCPtr, this);
  }

  /**
   * Get the Aspen build string.<br>
   * <br>
   * @return A string containing the Aspen build string.
   */
  public String getBuild() {
    return AspenJNI.AspenManager_getBuild(swigCPtr, this);
  }

  /**
   * Returns whether the <a href="#IProfileService">IProfileService</a> is supported or not.<br>
   * <br>
   * This method returns a bool indicating if the profile service is supported by<br>
   * the license key supplied at initialization of AspenManager.<br>
   * <br>
   * @return True when the ProfileService is supported, false when not supported.
   */
  public boolean supportsProfileService() {
    return AspenJNI.AspenManager_supportsProfileService(swigCPtr, this);
  }

  /**
   * Create a <a href="#IDeviceService">IDeviceService</a> for a specific model id.<br>
   * <br>
   * @param model_id The model id of the audio device.<br>
   * @return A pointer to an instance of a device service.
   */
  @Nullable
  public IDeviceService createDeviceService(int model_id) {
    long cPtr = AspenJNI.AspenManager_createDeviceService(swigCPtr, this, model_id);
    return (cPtr == 0) ? null : new IDeviceService(cPtr, true);
  }

  /**
   * Create a <a href="#IVirtualDeviceService">IVirtualDeviceService</a> for a specific model id.<br>
   * <br>
   * @param model_id The model id of the audio device.<br>
   * @param cbs A reference to a IVirtualDeviceServiceCallbacks implementation.<br>
   * @return A pointer to an instance of a virtual device service.
   */
  public IVirtualDeviceService createVirtualDeviceService(int model_id, IVirtualDeviceServiceCallbacks cbs) {
    try {
      long cPtr = AspenJNI.AspenManager_createVirtualDeviceService(swigCPtr, this, model_id, IVirtualDeviceServiceCallbacks.getCPtr(cbs), cbs);
      return (cPtr == 0) ? null : new IVirtualDeviceService(cPtr, true);
    } finally {
      vCallbackReference = cbs;
    }
  }

  /**
   * Returns whether an audio device is supported by APS.<br>
   * <br>
   * This method returns a bool indicating whether an audio device is<br>
   * supported by Aspen, given its model id. For audio devices using<br>
   * BLE, the model id is presented in the advertisement data.<br>
   * <br>
   * @param model_id The model id of the audio device.<br>
   * @return True when the audio device is supported by APS, false when not supported.
   */
  public boolean audioDeviceSupported(int model_id) {
    return AspenJNI.AspenManager_audioDeviceSupported__SWIG_0(swigCPtr, this, model_id);
  }

  /**
   * Returns whether a BR/EDR device is supported by APS.<br>
   * <br>
   * This method returns a bool indicating whether an audio device is<br>
   * supported by Aspen, given its BR/EDR UUID. This is for audio devices<br>
   * presenting themselves with BR/EDR UUID, i.e. using Bluetooth<br>
   * Classic.<br>
   * <br>
   * Note: Do not pass nullptr as bredr_uuid; C++ will try to<br>
   *       turn that into an std::string assuming it's a const char *,<br>
   *       which will end badly.<br>
   * <br>
   * @param bredr_uuid  The BR/EDR UUID for the audio device.<br>
   * @return True when the audio device is supported by APS, false when not supported.
   */
  public boolean audioDeviceSupported(String bredr_uuid) {
    return AspenJNI.AspenManager_audioDeviceSupported__SWIG_1(swigCPtr, this, bredr_uuid);
  }

  /**
   * Converts a BR/EDR UUID to an audio device model id.<br>
   * <br>
   * Note: Do not pass nullptr as bredr_uuid; C++ will try to turn that<br>
   *       into a std::string assuming it's a const char *, which will end badly.<br>
   * <br>
   * @param bredr_uuid The BR/EDR UUID for the audio device.<br>
   * @return The model id for the device if it exists, else 0.
   */
  public int modelIdFromBredrUuid(String bredr_uuid) {
    return AspenJNI.AspenManager_modelIdFromBredrUuid(swigCPtr, this, bredr_uuid);
  }

  /**
   * Returns a vector with the supported audio device model ids.<br>
   * <br>
   * The method returns all of the supported audio device model ids based on<br>
   * the license key supplied at initialization of AspenManager.<br>
   * <br>
   * @return An array containing the supported audio device model ids.
   */
  public UintVector supportedDeviceModelIds() {
    return new UintVector(AspenJNI.AspenManager_supportedDeviceModelIds(swigCPtr, this), true);
  }

  /**
   * Returns whether the <a href="#IEqualizerProfileService">IEqualizerProfileService</a> is supported or not.<br>
   * <br>
   * @return True when the EqualizerProfileService is supported, false when not supported.
   */
  public boolean supportsEqualizerProfileService() {
    return AspenJNI.AspenManager_supportsEqualizerProfileService(swigCPtr, this);
  }

  /**
   * Getter for the <a href="#IEqualizerProfileService">IEqualizerProfileService</a>.<br>
   * <br>
   * Gets an interface to the equalizer profile service, which can be used to manage<br>
   * equalizer profiles.<br>
   * <br>
   * @return A pointer to the equalizer profiler service.
   */
  public IEqualizerProfileService getEqualizerProfileService() {
    long cPtr = AspenJNI.AspenManager_getEqualizerProfileService(swigCPtr, this);
    return (cPtr == 0) ? null : new IEqualizerProfileService(cPtr, true);
  }

  protected void reset() {
    AspenJNI.AspenManager_reset(swigCPtr, this);
    vCallbackReference = null;
}

}
