/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

import android.os.Build;


/**
* Helper class for getting AspenManager as a singleton in an Android environment.
*
* Creates an AspenManager instance on first call to getManager and automatically provides the
* manager with the required environment information and license key. License key needs to be
* supplied as a system property for this to work. Either in build context or in code called
* before first call to getManager.
*
*/
public class Aspen {

    static private AspenManager aspenManager = null;

    static private void initialize() {
        String key = System.getProperty("ASPEN_LICENSE_KEY");
        if (key == null) {
             throw new IllegalStateException("Must set system property ASPEN_LICENSE_KEY before accessing Aspen");
        }
        String config_dir = System.getProperty("ASPEN_CONFIG_DIRECTORY");
        if (config_dir == null) {
            throw new IllegalStateException("Must set system property ASPEN_CONFIG_DIRECTORY before accessing Aspen");
        }

        System.loadLibrary("Aspen");
        Environment env = new Environment(Build.MANUFACTURER, Build.MODEL, "android",  Build.VERSION.RELEASE);
        AspenManager.init(key, env, config_dir);
    }

    /**
    * Returns a reference to the singleton AspenManager. If it does not exist it is created.
    *
    * @return      The singleton AspenManager object
    */
    static public synchronized AspenManager getManager() {
        if (aspenManager == null) {
            initialize();
        }
        aspenManager = AspenManager.getInstance();
        return aspenManager;
    }

    static public synchronized void resetManager() {
        if (aspenManager != null) {
            aspenManager.reset();
            aspenManager = null;
        }
    }

}
