/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class Audiogram {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Audiogram(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Audiogram obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Audiogram obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_Audiogram(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Audiogram(ByteVector left_channel, ByteVector right_channel) {
    this(AspenJNI.new_Audiogram(ByteVector.getCPtr(left_channel), left_channel, ByteVector.getCPtr(right_channel), right_channel), true);
  }

  /**
   * Get the audiogram for the left channel<br>
   * <br>
   * The vector contains the hearing threshold in dbHL at<br>
   * the following frequencies:<br>
   * - 250 Hz<br>
   * - 500 Hz<br>
   * - 1000 Hz<br>
   * - 2000 Hz<br>
   * - 4000 Hz<br>
   * - 8000 Hz<br>
   * @return std::vector&lt;int8_t&gt; The audiogram for the left channel.
   */
  public ByteVector getLeftChannel() {
    return new ByteVector(AspenJNI.Audiogram_getLeftChannel(swigCPtr, this), true);
  }

  /**
   * Get the audiogram for the right channel<br>
   * <br>
   * The vector contains the hearing threshold in dbHL at<br>
   * the following frequencies:<br>
   * - 250 Hz<br>
   * - 500 Hz<br>
   * - 1000 Hz<br>
   * - 2000 Hz<br>
   * - 4000 Hz<br>
   * - 8000 Hz<br>
   * @return std::vector&lt;int8_t&gt; The audiogram for the right channel.
   */
  public ByteVector getRightChannel() {
    return new ByteVector(AspenJNI.Audiogram_getRightChannel(swigCPtr, this), true);
  }

}
