/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum AudiodoTransparencyMode {
  MUSIC,
  VOICE,
  AMBIENT,
  ANSI3_22_2014;

  public final int swigValue() {
    return swigValue;
  }

  public static AudiodoTransparencyMode swigToEnum(int swigValue) {
    AudiodoTransparencyMode[] swigValues = AudiodoTransparencyMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AudiodoTransparencyMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AudiodoTransparencyMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyMode(AudiodoTransparencyMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

