/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Configuration for the Audiosphere feature.<br>
 * <br>
 * The AudiosphereIrConfig class encapsulates all parameters required to configure the<br>
 * <a href="#IAudiosphereIrCapability">IAudiosphereIrCapability</a>.<br>
 * <br>
 * Changes to an instance of this class do not take effect immediately. The updated configuration must be applied<br>
 * by calling <a href="#IAudiosphereIrCapability::set_config()">IAudiosphereIrCapability::set_config()</a>.
 */
public class AudiosphereIrConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AudiosphereIrConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudiosphereIrConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AudiosphereIrConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_AudiosphereIrConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a new default AudiosphereIrConfig object.
   */
  public AudiosphereIrConfig() {
    this(AspenJNI.new_AudiosphereIrConfig__SWIG_0(), true);
  }

  /**
   * Construct a new AudiosphereIrConfig object with data.<br>
   * <br>
   * @param presence The desired presence level.<br>
   * @param room_id The room configuration to activate.<br>
   * @param walls_present True if walls should be present, false otherwise.<br>
   * @param constellation The speaker constellation to use.<br>
   * @param angle_front_left The desired angle of the front left speaker.<br>
   * @param angle_front_right The desired angle of the front right speaker.<br>
   * @param angle_rear_left The desired angle of the rear left speaker.<br>
   * @param angle_rear_right The desired angle of the rear right speaker.<br>
   * @param gain_front_left The desired gain of the front left speaker.<br>
   * @param gain_front_right The desired gain of the front right speaker.<br>
   * @param gain_rear_left The desired gain of the rear left speaker.<br>
   * @param gain_rear_right The desired gain of the rear right speaker.
   */
  public AudiosphereIrConfig(short presence, short room_id, boolean walls_present, SpeakerConstellation constellation, short angle_front_left, short angle_front_right, short angle_rear_left, short angle_rear_right, short gain_front_left, short gain_front_right, short gain_rear_left, short gain_rear_right) {
    this(AspenJNI.new_AudiosphereIrConfig__SWIG_1(presence, room_id, walls_present, constellation.swigValue(), angle_front_left, angle_front_right, angle_rear_left, angle_rear_right, gain_front_left, gain_front_right, gain_rear_left, gain_rear_right), true);
  }

  /**
   * Sets the presence level<br>
   * <br>
   * The valid range is 0 to <a href="#AudiosphereIrConfig::get_max_presence()">AudiosphereIrConfig::get_max_presence()</a>.<br>
   * Values outside the valid range will be clamped.<br>
   * <br>
   * @param presence The desired presence level.
   */
  public void setPresence(short presence) {
    AspenJNI.AudiosphereIrConfig_setPresence(swigCPtr, this, presence);
  }

  /**
   * Sets the active room configuration<br>
   * <br>
   * The room ID refers to a predefined configuration built into the firmware.<br>
   * <br>
   * @param room_id The room configuration to activate.
   */
  public void setRoomId(short room_id) {
    AspenJNI.AudiosphereIrConfig_setRoomId(swigCPtr, this, room_id);
  }

  /**
   * Enables or disables the presence of walls<br>
   * <br>
   * @param walls_present True if walls should be present, false otherwise.
   */
  public void setWallsPresent(boolean walls_present) {
    AspenJNI.AudiosphereIrConfig_setWallsPresent(swigCPtr, this, walls_present);
  }

  /**
   * Sets the active speaker constellation<br>
   * <br>
   * Selects which predefined speaker layout configuration to use.<br>
   * <br>
   * @param constellation The speaker constellation to use.
   */
  public void setSpeakerConstellation(SpeakerConstellation constellation) {
    AspenJNI.AudiosphereIrConfig_setSpeakerConstellation(swigCPtr, this, constellation.swigValue());
  }

  /**
   * Sets the angular position of a speaker relative to the listener<br>
   * <br>
   * The valid range is -180 to 180 degrees. Values outside the valid range will be clamped.<br>
   * <br>
   * The listener is assumed to be positioned at the center of the coordinate system,<br>
   * facing 0 degrees. An angle of 0 degrees places the speaker directly in front<br>
   * of the listener.<br>
   * <br>
   * Example: For a symmetrical four-speaker constellation with a front spread<br>
   * of 20 degrees:<br>
   * <br>
   * Front left:   20 degrees<br>
   * Front right: -20 degrees<br>
   * Rear left:   160 degrees<br>
   * Rear right: -160 degrees<br>
   * <br>
   * @param position The speaker position to configure.<br>
   * @param angle_degrees The desired angle in degrees.
   */
  public void setSpeakerAngle(SpeakerPosition position, short angle_degrees) {
    AspenJNI.AudiosphereIrConfig_setSpeakerAngle(swigCPtr, this, position.swigValue(), angle_degrees);
  }

  /**
   * Sets all the angular positions for all four speakers derived from the front right angle<br>
   * <br>
   * This sets all four angles based on Audiodo's default recommendation.<br>
   * The valid range is 0 to 90 degrees. Values outside the valid range will be clamped.<br>
   * <br>
   * The listener is assumed to be positioned at the center of the coordinate system,<br>
   * facing 0 degrees. An angle of 0 degrees places the speaker directly in front<br>
   * of the listener.<br>
   * <br>
   * Example: For a symmetrical four-speaker constellation with a front right speaker at 20 degrees:<br>
   * <br>
   * Front left:   -20 degrees<br>
   * Front right:   20 degrees<br>
   * Rear left:   -160 degrees<br>
   * Rear right:   160 degrees<br>
   * <br>
   * @param angle_degrees The desired front right angle in degrees.
   */
  public void setSpeakerAnglesDerivedFromFrontRight(short angle_degrees) {
    AspenJNI.AudiosphereIrConfig_setSpeakerAnglesDerivedFromFrontRight(swigCPtr, this, angle_degrees);
  }

  /**
   * Sets the gain level of a speaker<br>
   * <br>
   * The valid range is 0-100. Values outside the valid range will be clamped.<br>
   * <br>
   * @param position The speaker position to configure.<br>
   * @param gain_percent The desired gain in percent.
   */
  public void setSpeakerGain(SpeakerPosition position, short gain_percent) {
    AspenJNI.AudiosphereIrConfig_setSpeakerGain(swigCPtr, this, position.swigValue(), gain_percent);
  }

  /**
   * Returns the current presence level<br>
   * <br>
   * @return The presence level.
   */
  public short getPresence() {
    return AspenJNI.AudiosphereIrConfig_getPresence(swigCPtr, this);
  }

  /**
   * Returns the currently active room configuration<br>
   * <br>
   * @return The active room configuration.
   */
  public short getRoomId() {
    return AspenJNI.AudiosphereIrConfig_getRoomId(swigCPtr, this);
  }

  /**
   * Returns whether walls are currently present or not<br>
   * <br>
   * @return True if walls are present, false otherwise.
   */
  public boolean getWallsPresent() {
    return AspenJNI.AudiosphereIrConfig_getWallsPresent(swigCPtr, this);
  }

  /**
   * Returns the currently active speaker constellation<br>
   * <br>
   * @return The active speaker constellation.
   */
  public SpeakerConstellation getSpeakerConstellation() {
    return SpeakerConstellation.swigToEnum(AspenJNI.AudiosphereIrConfig_getSpeakerConstellation(swigCPtr, this));
  }

  /**
   * Returns the current angle of a specific speaker<br>
   * <br>
   * See <a href="#AudiosphereIrConfig::set_speaker_angle()">AudiosphereIrConfig::set_speaker_angle()</a> for details on the coordinate system and<br>
   * value conventions.<br>
   * <br>
   * @param position The speaker position to get the angle for.<br>
   * @return The current speaker angle in degrees.
   */
  public short getSpeakerAngle(SpeakerPosition position) {
    return AspenJNI.AudiosphereIrConfig_getSpeakerAngle(swigCPtr, this, position.swigValue());
  }

  /**
   * Returns the current gain of a specific speaker<br>
   * <br>
   * @param position The speaker position to get the gain for.<br>
   * @return The current speaker gain as a percentage.
   */
  public short getSpeakerGain(SpeakerPosition position) {
    return AspenJNI.AudiosphereIrConfig_getSpeakerGain(swigCPtr, this, position.swigValue());
  }

  /**
   * Returns the max presence level<br>
   * <br>
   * @return The max presence level.
   */
  public static short getMaxPresence() {
    return AspenJNI.AudiosphereIrConfig_getMaxPresence();
  }

}
