/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum AudiodoTransparencyFeedbackSuppressionMode {
  LEAST,
  LESS,
  NORMAL,
  MORE,
  MOST;

  public final int swigValue() {
    return swigValue;
  }

  public static AudiodoTransparencyFeedbackSuppressionMode swigToEnum(int swigValue) {
    AudiodoTransparencyFeedbackSuppressionMode[] swigValues = AudiodoTransparencyFeedbackSuppressionMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AudiodoTransparencyFeedbackSuppressionMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AudiodoTransparencyFeedbackSuppressionMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyFeedbackSuppressionMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyFeedbackSuppressionMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyFeedbackSuppressionMode(AudiodoTransparencyFeedbackSuppressionMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

