/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum AudiodoTransparencyType {
  GENERIC,
  AUDIODO,
  NAL_NL2,
  ANSI3_22_2014_FOG,
  ANSI3_22_2014_RTS,
  COUNT;

  public final int swigValue() {
    return swigValue;
  }

  public static AudiodoTransparencyType swigToEnum(int swigValue) {
    AudiodoTransparencyType[] swigValues = AudiodoTransparencyType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AudiodoTransparencyType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AudiodoTransparencyType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AudiodoTransparencyType(AudiodoTransparencyType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

