/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class ByteVector extends java.util.AbstractList<Byte> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ByteVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ByteVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ByteVector(byte[] initialElements) {
    this();
    reserve(initialElements.length);

    for (byte element : initialElements) {
      add(element);
    }
  }

  public ByteVector(Iterable<Byte> initialElements) {
    this();
    for (byte element : initialElements) {
      add(element);
    }
  }

  public Byte get(int index) {
    return doGet(index);
  }

  public Byte set(int index, Byte e) {
    return doSet(index, e);
  }

  public boolean add(Byte e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Byte e) {
    modCount++;
    doAdd(index, e);
  }

  public Byte remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ByteVector() {
    this(AspenJNI.new_ByteVector__SWIG_0(), true);
  }

  public ByteVector(ByteVector other) {
    this(AspenJNI.new_ByteVector__SWIG_1(ByteVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AspenJNI.ByteVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AspenJNI.ByteVector_clear(swigCPtr, this);
  }

  public ByteVector(int count, byte value) {
    this(AspenJNI.new_ByteVector__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return AspenJNI.ByteVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AspenJNI.ByteVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AspenJNI.ByteVector_doSize(swigCPtr, this);
  }

  private void doAdd(byte x) {
    AspenJNI.ByteVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, byte x) {
    AspenJNI.ByteVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private byte doRemove(int index) {
    return AspenJNI.ByteVector_doRemove(swigCPtr, this, index);
  }

  private byte doGet(int index) {
    return AspenJNI.ByteVector_doGet(swigCPtr, this, index);
  }

  private byte doSet(int index, byte val) {
    return AspenJNI.ByteVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AspenJNI.ByteVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
