/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum CalibrationCapabilityAbortReason {
  /**
   *  Abort reason not known, some older firmwares does not report why the calibration was aborted 
   */
  UNKNOWN,
  /**
   *  Incoming call 
   */
  INCOMING_CALL,
  /**
   *  The calibration was paused for too long. 
   */
  PAUSE_TIMEOUT,
  /**
   *  The device failed to prepare for calibration to start. 
   */
  PREPARATION_FAILED;

  public final int swigValue() {
    return swigValue;
  }

  public static CalibrationCapabilityAbortReason swigToEnum(int swigValue) {
    CalibrationCapabilityAbortReason[] swigValues = CalibrationCapabilityAbortReason.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CalibrationCapabilityAbortReason swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CalibrationCapabilityAbortReason.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityAbortReason() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityAbortReason(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityAbortReason(CalibrationCapabilityAbortReason swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

