/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class CalibrationCapabilityProgressData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CalibrationCapabilityProgressData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrationCapabilityProgressData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CalibrationCapabilityProgressData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_CalibrationCapabilityProgressData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  The current intensity index for the frequency being played, 0-indexed.
   */
  public void setIntensity_index(short value) {
    AspenJNI.CalibrationCapabilityProgressData_intensity_index_set(swigCPtr, this, value);
  }

  /**
   *  The current intensity index for the frequency being played, 0-indexed.
   */
  public short getIntensity_index() {
    return AspenJNI.CalibrationCapabilityProgressData_intensity_index_get(swigCPtr, this);
  }

  /**
   *  The number of intensities that will be played for each frequency. This may change<br>
   *  based on the first choice for each frequency (if answering that tone was heard or not). 
   */
  public void setIntensity_count(short value) {
    AspenJNI.CalibrationCapabilityProgressData_intensity_count_set(swigCPtr, this, value);
  }

  /**
   *  The number of intensities that will be played for each frequency. This may change<br>
   *  based on the first choice for each frequency (if answering that tone was heard or not). 
   */
  public short getIntensity_count() {
    return AspenJNI.CalibrationCapabilityProgressData_intensity_count_get(swigCPtr, this);
  }

  /**
   *  The current frequency index for the channel being played, 0-indexed. 
   */
  public void setFrequency_index(short value) {
    AspenJNI.CalibrationCapabilityProgressData_frequency_index_set(swigCPtr, this, value);
  }

  /**
   *  The current frequency index for the channel being played, 0-indexed. 
   */
  public short getFrequency_index() {
    return AspenJNI.CalibrationCapabilityProgressData_frequency_index_get(swigCPtr, this);
  }

  /**
   *  The number of frequencies that will be played for each channel. 
   */
  public void setFrequency_count(short value) {
    AspenJNI.CalibrationCapabilityProgressData_frequency_count_set(swigCPtr, this, value);
  }

  /**
   *  The number of frequencies that will be played for each channel. 
   */
  public short getFrequency_count() {
    return AspenJNI.CalibrationCapabilityProgressData_frequency_count_get(swigCPtr, this);
  }

  /**
   *  The current channel index being played, 0-indexed. 
   */
  public void setChannel_index(short value) {
    AspenJNI.CalibrationCapabilityProgressData_channel_index_set(swigCPtr, this, value);
  }

  /**
   *  The current channel index being played, 0-indexed. 
   */
  public short getChannel_index() {
    return AspenJNI.CalibrationCapabilityProgressData_channel_index_get(swigCPtr, this);
  }

  /**
   *  The number of channels. 
   */
  public void setChannel_count(short value) {
    AspenJNI.CalibrationCapabilityProgressData_channel_count_set(swigCPtr, this, value);
  }

  /**
   *  The number of channels. 
   */
  public short getChannel_count() {
    return AspenJNI.CalibrationCapabilityProgressData_channel_count_get(swigCPtr, this);
  }

  public CalibrationCapabilityProgressData() {
    this(AspenJNI.new_CalibrationCapabilityProgressData(), true);
  }

}
