/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum CalibrationCapabilityStatus {
  /**
   *  Initial state 
   */
  IDLE,
  /**
   *  Calibration is paused, can be resumed 
   */
  PAUSED,
  /**
   *  Calibration is running 
   */
  RUNNING,
  /**
   *  Calibration has completed 
   */
  COMPLETED;

  public final int swigValue() {
    return swigValue;
  }

  public static CalibrationCapabilityStatus swigToEnum(int swigValue) {
    CalibrationCapabilityStatus[] swigValues = CalibrationCapabilityStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CalibrationCapabilityStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CalibrationCapabilityStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CalibrationCapabilityStatus(CalibrationCapabilityStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

