/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Capability Support Status
 */
public enum CapabilitySupportStatus {
  NOT_SUPPORTED,
  SUPPORTED,
  CONNECTION_REQUIRED;

  public final int swigValue() {
    return swigValue;
  }

  public static CapabilitySupportStatus swigToEnum(int swigValue) {
    CapabilitySupportStatus[] swigValues = CapabilitySupportStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CapabilitySupportStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CapabilitySupportStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CapabilitySupportStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CapabilitySupportStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CapabilitySupportStatus(CapabilitySupportStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

