/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum DeviceType {
  HEADSET,
  EARBUDS;

  public final int swigValue() {
    return swigValue;
  }

  public static DeviceType swigToEnum(int swigValue) {
    DeviceType[] swigValues = DeviceType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (DeviceType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + DeviceType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private DeviceType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private DeviceType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private DeviceType(DeviceType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

