/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The Environment class<br>
 * <br>
 * The environment class holds the environment variables, such as manufacturer,<br>
 * model, os and os version.
 */
public class Environment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Environment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Environment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Environment obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_Environment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Environment(String manufacturer, String model, String os, String version) {
    this(AspenJNI.new_Environment(manufacturer, model, os, version), true);
  }

  public String getManufacturer() {
    return AspenJNI.Environment_getManufacturer(swigCPtr, this);
  }

  public String getModel() {
    return AspenJNI.Environment_getModel(swigCPtr, this);
  }

  public String getOs() {
    return AspenJNI.Environment_getOs(swigCPtr, this);
  }

  public String getVersion() {
    return AspenJNI.Environment_getVersion(swigCPtr, this);
  }

}
