/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * One position's X+Y values in a [-1, -1, 1, 1] coordinate system
 */
public class EqualizerPos {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EqualizerPos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqualizerPos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqualizerPos obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_EqualizerPos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a new default Equalizer Position object<br>
   * <br>
   * Default constructor sets positions to zero.
   */
  public EqualizerPos() {
    this(AspenJNI.new_EqualizerPos__SWIG_0(), true);
  }

  /**
   * Construct a new Equalizer Position object<br>
   * <br>
   * Any values outside the limits will be clamped.<br>
   *  0.0 &lt;= X &lt;= 1.0<br>
   * -1.0 &lt;= Y &lt;= 1.0<br>
   * <br>
   * @param x The value of the x-axle.<br>
   * @param y The value of the y-axle.
   */
  public EqualizerPos(float x, float y) {
    this(AspenJNI.new_EqualizerPos__SWIG_1(x, y), true);
  }

  /**
   * Get the position on the x-axle.<br>
   * <br>
   * @return Returns a value between 0.0 to 1.0
   */
  public float getX() {
    return AspenJNI.EqualizerPos_getX(swigCPtr, this);
  }

  /**
   * Get the position on the y-axle.<br>
   * <br>
   * @return Returns a value between -1.0 to 1.0
   */
  public float getY() {
    return AspenJNI.EqualizerPos_getY(swigCPtr, this);
  }

  /**
   * Returns a string representation of the object's state<br>
   * <br>
   * @return std::string A string representing the current state of the object
   */
  public String toString() {
    return AspenJNI.EqualizerPos_toString(swigCPtr, this);
  }

}
