/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Equalizer Profile that contains more than just an EqualizerConfiguration<br>
 * <br>
 * Used to be able to store EqualizerConfiguration along with a name.
 */
public class EqualizerProfile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EqualizerProfile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqualizerProfile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqualizerProfile obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_EqualizerProfile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a new Equalizer Profile object with all possible data<br>
   * <br>
   * Sets up an equalizer profile with id, name, eq_config and eq_positions.<br>
   * The id is on a standard UUID hexadecimal format. If the ID is invalid,<br>
   * an exception will be thrown.<br>
   * <br>
   * @param id A standard UUID on hexadecimal format<br>
   * @param name The name of the EqualizerProfile<br>
   * @param eq_config The EqualizerConfiguration object of the EqualizerProfile<br>
   * @param eq_positions The EqualizerPositions object of the EqualizerProfile
   */
  public EqualizerProfile(String id, String name, EqualizerConfiguration eq_config, EqualizerPositions eq_positions) {
    this(AspenJNI.new_EqualizerProfile(id, name, EqualizerConfiguration.getCPtr(eq_config), eq_config, EqualizerPositions.getCPtr(eq_positions), eq_positions), true);
  }

  /**
   * Get the id of the profile<br>
   * <br>
   * @return Returns a UUID as a string
   */
  public String getId() {
    return AspenJNI.EqualizerProfile_getId(swigCPtr, this);
  }

  /**
   * Get the name of the profile<br>
   * <br>
   * @return Returns the name as a string
   */
  public String getName() {
    return AspenJNI.EqualizerProfile_getName(swigCPtr, this);
  }

  /**
   * Get the EQ config of the profile<br>
   * <br>
   * @return Returns an EqualizerConfiguration object
   */
  public EqualizerConfiguration getConfig() {
    return new EqualizerConfiguration(AspenJNI.EqualizerProfile_getConfig(swigCPtr, this), true);
  }

  /**
   * Get the EQ positions of the profile<br>
   * <br>
   * @return Returns an EqualizerPositions object
   */
  public EqualizerPositions getPositions() {
    return new EqualizerPositions(AspenJNI.EqualizerProfile_getPositions(swigCPtr, this), true);
  }

  /**
   * Set the name of the profile<br>
   * <br>
   * @param name The name as a string
   */
  public void setName(String name) {
    AspenJNI.EqualizerProfile_setName(swigCPtr, this, name);
  }

  /**
   * Set the EQ config and EQ positions of the profile<br>
   * <br>
   * @param config An EqualizerConfiguration object<br>
   * @param positions An EqualizerPositions object
   */
  public void setConfigAndPositions(EqualizerConfiguration config, EqualizerPositions positions) {
    AspenJNI.EqualizerProfile_setConfigAndPositions(swigCPtr, this, EqualizerConfiguration.getCPtr(config), config, EqualizerPositions.getCPtr(positions), positions);
  }

}
