/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

import java.util.List;

/**
 * Stores positions for EQ graph handles/gain tilt<br>
 * <br>
 * Used to store positions for handles that make up an EQ graph curve as<br>
 * well as a value of a gain tilt. This is provided by Aspen to make it<br>
 * easier to implement an EQ Graph that uses a number of handle positions<br>
 * instead of frequency/gain value sliders as a traditional EQ is built up.
 */
public class EqualizerPositions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EqualizerPositions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqualizerPositions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqualizerPositions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_EqualizerPositions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a new default Equalizer Positions object.<br>
   * <br>
   * Default constructor sets all positions to zero.
   */
  public EqualizerPositions() {
    this(AspenJNI.new_EqualizerPositions__SWIG_0(), true);
  }

  /**
   * Construct a new EqualizerPositions object from a vector of positions and a tilt gain handle<br>
   * <br>
   * @param positions A vector of EqualizerPos objects<br>
   * @param tilt_gain_handle The tilt gain handle<br>
   * <br>
   * The given tilt gain handle will be clamped to ensure it is within the range [MIN_VALUE_TILT_GAIN_HANDLE, MAX_VALUE_TILT_GAIN_HANDLE]
   */
  public EqualizerPositions(List<EqualizerPos> positions, float tilt_gain_handle) {
    this(AspenJNI.new_EqualizerPositions__SWIG_1(positions, tilt_gain_handle), true);
  }

  /**
   * Get the position handles<br>
   * <br>
   * @return Returns a vector of EqualizerPos objects
   */
  public List<EqualizerPos> getPositionHandles() {
    return AspenJNI.EqualizerPositions_getPositionHandles(swigCPtr, this);
}

  /**
   * Get the tilt gain handle<br>
   * <br>
   * @return Returns a float value representing the value of the tilt gain handle
   */
  public float getTiltGainHandle() {
    return AspenJNI.EqualizerPositions_getTiltGainHandle(swigCPtr, this);
  }

  /**
   * Returns a string representation of the object's state<br>
   * <br>
   * @return std::string A string representing the current state of the object
   */
  public String toString() {
    return AspenJNI.EqualizerPositions_toString(swigCPtr, this);
  }

}
