/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Represents a configuration for an equalizer.<br>
 * <br>
 * The configuration contains 9 gains for different frequency bands. The gains are in centibels<br>
 * with a range of -120 to 120
 */
public class EqualizerConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EqualizerConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqualizerConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqualizerConfiguration obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_EqualizerConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a new default Equalizer Configuration object.<br>
   * <br>
   * The default configuration sets all gains to zero.
   */
  public EqualizerConfiguration() {
    this(AspenJNI.new_EqualizerConfiguration__SWIG_0(), true);
  }

  /**
   * Construct a new Equalizer Configuration object with data.<br>
   * <br>
   * @param gain_63Hz    The gain for the frequency 63Hz.<br>
   * @param gain_125Hz   The gain for the frequency 125Hz.<br>
   * @param gain_250Hz   The gain for the frequency 250Hz.<br>
   * @param gain_500Hz   The gain for the frequency 500Hz.<br>
   * @param gain_1000Hz  The gain for the frequency 1000Hz.<br>
   * @param gain_2000Hz  The gain for the frequency 2000Hz.<br>
   * @param gain_4000Hz  The gain for the frequency 4000Hz.<br>
   * @param gain_8000Hz  The gain for the frequency 8000Hz.<br>
   * @param gain_16000Hz The gain for the frequency 16000Hz.
   */
  public EqualizerConfiguration(byte gain_63Hz, byte gain_125Hz, byte gain_250Hz, byte gain_500Hz, byte gain_1000Hz, byte gain_2000Hz, byte gain_4000Hz, byte gain_8000Hz, byte gain_16000Hz) {
    this(AspenJNI.new_EqualizerConfiguration__SWIG_1(gain_63Hz, gain_125Hz, gain_250Hz, gain_500Hz, gain_1000Hz, gain_2000Hz, gain_4000Hz, gain_8000Hz, gain_16000Hz), true);
  }

  /**
   *  Set the gain of the frequency 63 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set63hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set63hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 125 Hz.<br>
   * <br>
   * This method sets the gain of the frequency 125 Hz.<br>
   * @param gain The gain as an int8_t.
   */
  public void set125hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set125hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 250 Hz.<br>
   * <br>
   * This method sets the gain of the frequency 250 Hz.<br>
   * @param gain The gain as an int8_t.
   */
  public void set250hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set250hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 500 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set500hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set500hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 1000 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set1000hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set1000hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 2000 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set2000hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set2000hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 4000 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set4000hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set4000hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 8000 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set8000hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set8000hz(swigCPtr, this, gain);
  }

  /**
   *  Set the gain of the frequency 16000 Hz.<br>
   * <br>
   * @param gain The gain as an int8_t.
   */
  public void set16000hz(byte gain) {
    AspenJNI.EqualizerConfiguration_set16000hz(swigCPtr, this, gain);
  }

  /**
   *  Get the gain of the frequency 63 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 63 Hz as an int8_t.
   */
  public byte get63hz() {
    return AspenJNI.EqualizerConfiguration_get63hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 125 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 125 Hz as an int8_t.
   */
  public byte get125hz() {
    return AspenJNI.EqualizerConfiguration_get125hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 250 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 250 Hz as an int8_t.
   */
  public byte get250hz() {
    return AspenJNI.EqualizerConfiguration_get250hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 500 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 500 Hz as an int8_t.
   */
  public byte get500hz() {
    return AspenJNI.EqualizerConfiguration_get500hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 1000 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 1000 Hz as an int8_t.
   */
  public byte get1000hz() {
    return AspenJNI.EqualizerConfiguration_get1000hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 2000 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 2000 Hz as an int8_t.
   */
  public byte get2000hz() {
    return AspenJNI.EqualizerConfiguration_get2000hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 4000 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 4000 Hz as an int8_t.
   */
  public byte get4000hz() {
    return AspenJNI.EqualizerConfiguration_get4000hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 8000 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 8000 Hz as an int8_t.
   */
  public byte get8000hz() {
    return AspenJNI.EqualizerConfiguration_get8000hz(swigCPtr, this);
  }

  /**
   *  Get the gain of the frequency 16000 Hz.<br>
   * <br>
   * @return Returns the gain of the frequency 16000 Hz as an int8_t.
   */
  public byte get16000hz() {
    return AspenJNI.EqualizerConfiguration_get16000hz(swigCPtr, this);
  }

}
