/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class FloatMatrix extends java.util.AbstractList<FloatVector> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FloatMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FloatMatrix obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_FloatMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FloatMatrix(FloatVector[] initialElements) {
    this();
    reserve(initialElements.length);

    for (FloatVector element : initialElements) {
      add(element);
    }
  }

  public FloatMatrix(Iterable<FloatVector> initialElements) {
    this();
    for (FloatVector element : initialElements) {
      add(element);
    }
  }

  public FloatVector get(int index) {
    return doGet(index);
  }

  public FloatVector set(int index, FloatVector e) {
    return doSet(index, e);
  }

  public boolean add(FloatVector e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, FloatVector e) {
    modCount++;
    doAdd(index, e);
  }

  public FloatVector remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public FloatMatrix() {
    this(AspenJNI.new_FloatMatrix__SWIG_0(), true);
  }

  public FloatMatrix(FloatMatrix other) {
    this(AspenJNI.new_FloatMatrix__SWIG_1(FloatMatrix.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AspenJNI.FloatMatrix_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AspenJNI.FloatMatrix_clear(swigCPtr, this);
  }

  public FloatMatrix(int count, FloatVector value) {
    this(AspenJNI.new_FloatMatrix__SWIG_2(count, FloatVector.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AspenJNI.FloatMatrix_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AspenJNI.FloatMatrix_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AspenJNI.FloatMatrix_doSize(swigCPtr, this);
  }

  private void doAdd(FloatVector x) {
    AspenJNI.FloatMatrix_doAdd__SWIG_0(swigCPtr, this, FloatVector.getCPtr(x), x);
  }

  private void doAdd(int index, FloatVector x) {
    AspenJNI.FloatMatrix_doAdd__SWIG_1(swigCPtr, this, index, FloatVector.getCPtr(x), x);
  }

  private FloatVector doRemove(int index) {
    return new FloatVector(AspenJNI.FloatMatrix_doRemove(swigCPtr, this, index), true);
  }

  private FloatVector doGet(int index) {
    return new FloatVector(AspenJNI.FloatMatrix_doGet(swigCPtr, this, index), false);
  }

  private FloatVector doSet(int index, FloatVector val) {
    return new FloatVector(AspenJNI.FloatMatrix_doSet(swigCPtr, this, index, FloatVector.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AspenJNI.FloatMatrix_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
