/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum Gender {
  WOMAN(0),
  MAN(1),
  NON_BINARY(2),
  PREFER_NOT_TO_SAY(3);

  public final int swigValue() {
    return swigValue;
  }

  public static Gender swigToEnum(int swigValue) {
    Gender[] swigValues = Gender.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Gender swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Gender.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Gender() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Gender(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Gender(Gender swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

