/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 *  The ANC capability<br>
 * <br>
 * This class is an interface to the ANC capability available on a DeviceService.<br>
 * It can be used to set a headset's ANC on, off, and in transparency mode, as well as<br>
 * getting the current state.<br>
 * <br>
 * The caller should implement a subclass of <a href="#IPropertyObserver">IPropertyObserver</a> to get the asynchronous<br>
 * result of some of the method calls in this class.
 */
public class IAncCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IAncCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IAncCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAncCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IAncCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Set ANC mode on the audio device<br>
   * <br>
   * This method sets the ANC on the connected remote audio device to the desired state.<br>
   * <br>
   * A successful operation will result in an event in the observer's propertyChanged()<br>
   * method. The event that matches this call is get_observable_event_set_anc_mode(),<br>
   * and the subject passed contains no additional information (an empty string).<br>
   * <br>
   * Initial errors are communicated through the boolean return value, asynchronous errors<br>
   * will result in the device session being terminated, and the user will have to determine<br>
   * proper cause of action.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the AncCapability,<br>
   * it will return false until that request is processed. Listen to the events to know<br>
   * when a request is done.<br>
   * <br>
   * @param anc_mode The AncMode to set on the audio device<br>
   * @return True if the initial handling went well, false if something immediately went wrong.
   */
  public boolean setAncMode(AncMode anc_mode) {
    return AspenJNI.IAncCapability_setAncMode(swigCPtr, this, anc_mode.swigValue());
  }

  /**
   *  Get the ANC mode<br>
   * <br>
   * This method returns the current ANC state of the audio device, or – if the  audio device has<br>
   * disconnected – the last known state.<br>
   * <br>
   * @return The anc mode of the audio device.
   */
  public AncMode getAncMode() {
    return AncMode.swigToEnum(AspenJNI.IAncCapability_getAncMode(swigCPtr, this));
  }

  /**
   *  Check if remote audio device status is up to date<br>
   * <br>
   * This method allows the Aspen user to check if the remote audio device status is in sync,<br>
   * i.e. whether the ANC state is up to date. When disconnected, get_anc_mode() will return<br>
   * the status from when the audio device was last connected.<br>
   * <br>
   * When not in sync, that means that the current information might or might not<br>
   * properly reflect the status in the audio device – we just don't know, and the status<br>
   * we have is what we last knew to be true.<br>
   * <br>
   * @return True if the remote audio device status is in sync, false if not in sync.
   */
  public boolean ancModeInSync() {
    return AspenJNI.IAncCapability_ancModeInSync(swigCPtr, this);
  }

  /**
   * Check if the anc mode is supported<br>
   * <br>
   * @param mode The anc mode to check whether it is supported or not.<br>
   * <br>
   * @return Returns a boolean specifying whether the mode is supported or not.
   */
  public boolean isModeSupported(AncMode mode) {
    return AspenJNI.IAncCapability_isModeSupported(swigCPtr, this, mode.swigValue());
  }

  /**
   *  The event for when an audio device's ANC state has been set<br>
   * <br>
   * When set_anc_mode() has been successfully completed, this event is sent to<br>
   * the IPropertyObserver property_changed().<br>
   * <br>
   * This method can be used to get the string constant that identifies the event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetAncMode() {
    return AspenJNI.IAncCapability_getObservableEventSetAncMode();
  }

  /**
   *  The event for when an audio device's ANC state has been received from the headset<br>
   * <br>
   * When AncCapability has connected to a headset with Audiodo ANC support, the device's<br>
   * ANC state is requested. Upon successful reception of the ANC state, this event is<br>
   * sent to the IPropertyObserver property_changed().<br>
   * <br>
   * This method can be used to get the string constant that identifies the event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventReceivedAncMode() {
    return AspenJNI.IAncCapability_getObservableEventReceivedAncMode();
  }

}
