/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

import android.content.Context;
import android.util.Log;

import java.lang.reflect.Method;
import java.util.Map;
import java.lang.reflect.InvocationTargetException;

/**
 * The Audiodo Transparency capability<br>
 * <br>
 * This class is an interface to the Audiodo transparency capability<br>
 * available on a <a href="#IDeviceService">IDeviceService</a>. It can be used to configure the<br>
 * Audiodo transparency. It does not however control the state of the<br>
 * transparency, see <a href="#IAncCapability">IAncCapability</a> for that.<br>
 * <br>
 * On session established the capability will start a synchronize process<br>
 * with the remote device. During this time most of the API calls will be<br>
 * blocked. When sync is complete the observer event<br>
 * <a href="#get_observable_event_sync_complete">get_observable_event_sync_complete</a> will be sent.
 */
public class IAudiodoTransparencyCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IAudiodoTransparencyCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IAudiodoTransparencyCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAudiodoTransparencyCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IAudiodoTransparencyCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

    /**
     * The NalNl2Data class.<br>
     * <br>
     * The class holds relevant data needed for the NalNl2 library.
     */
    public static class NalNl2Data {
        private boolean hasExperience;
        private boolean isTonalLanguage;
        private String profileId;

        // Constructor
        public NalNl2Data(boolean hasExperience, boolean isTonalLanguage, String profileId) {
            this.hasExperience = hasExperience;
            this.isTonalLanguage = isTonalLanguage;
            this.profileId = profileId;
        }

        /**
         * Getter for whether the customer has experience with hearing aids.<br>
         * <br>
         * @return True if the customer has experience with hearing aids, false otherwise.
         */
        public boolean hasExperience() {
            return hasExperience;
        }

        /**
         * Setter for specifying whether the customer has experience with hearing aids.<br>
         * <br>
         * @param hasExperience Boolean indicating whether the customer has experience with hearing aids (true) or not (false).
         */
        public void setExperience(boolean hasExperience) {
            this.hasExperience = hasExperience;
        }

       /**
        * Getter for checking if the user uses a tonal language.<br>
        * <br>
        * @return True if the user uses a tonal language, false otherwise.
        */
        public boolean isTonalLanguage() {
            return isTonalLanguage;
        }

        /**
         * Setter for specifying if the user uses a tonal language.<br>
         * <br>
         * @param isTonalLanguage True if the user uses a tonal language, false otherwise.
         */
        public void setTonalLanguage(boolean isTonalLanguage) {
            this.isTonalLanguage = isTonalLanguage;
        }

        /**
         * Getter for the profile ID.<br>
         * <br>
         * @return The profile ID as a string.
         */
        public String getProfileId() {
            return profileId;
        }
    }

    /**
    *  brief Converts a double[][] matrix to a FloatMatrix<br>
    * <br>
    * @param matrix The double[][] matrix to convert<br>
    * @return Returns the passed in matrix as a FloatMatrix
    */
    private FloatMatrix convertToFloatMatrix(double[][] matrix) {
        FloatMatrix float_matrix = new FloatMatrix();

    for (double[] row : matrix) {
        FloatVector floatVectorRow = new FloatVector();
        for (double value : row) {
            floatVectorRow.add((float) value);
        }
        float_matrix.add(floatVectorRow);
    }
    return float_matrix;
    }

    /**
    *  brief Converts an aspen::Gender to a corresponding NalNl2 gender integer representation<br>
    * <br>
    * @param gender The aspen::Gender enum value to be converted<br>
    * @return An integer corresponding to the NalNl2 gender representation.
    */
    private Integer convertAspenGenderToNalNl2Gender(Gender gender) {
        switch(gender) {
            case WOMAN: return 2;
            case MAN: return 1;
            case NON_BINARY: return 0;
            case PREFER_NOT_TO_SAY: return 0;
            default:
                throw new IllegalArgumentException("Unexpected value: " + gender);
        }
    }

    /**
    * Set NAL-NL2 personalization transparency type<br>
    * <br>
    * An asynchronous request to set NAL-NL2 personalization transparency type.
    *
    * It will use the<br>
    * profile with the matching profile id in the NalNl2Data object that is passed in to<br>
    * this function. If the profile is not found, nothing will happen.<br>
    * <br>
    * Observers will be notified with event <a href="#get_observable_event_set_type_nal_nl2_confirmation">get_observable_event_set_type_nal_nl2_confirmation</a><br>
    * when the change has been confirmed by the remote device.<br>
    * @param mode The transparency mode to use
    * @param nalNl2Data A NalNl2Data object containing needed meta data.<br>
    * @param applicationContext The application context.
    */
    public void setTypeNalNl2(AudiodoTransparencyMode mode, NalNl2Data nalNl2Data, Context applicationContext) {
        try {
            AspenManager aspen = Aspen.getManager();

            IProfileService profile_service = aspen.getProfileService();

            ProfileData profile = profile_service.getProfile(nalNl2Data.profileId);
            if (profile == null) {
                throw new IllegalArgumentException("Profile not found for ID: " + nalNl2Data.profileId);
            }

            if (mode == null) {
                throw new IllegalArgumentException("No mode set");
            }

            Gender gender = profile.getGender();
            Audiogram audiogram = profile.getAudiogram();

            Integer[] audiogramChannelLeft = new Integer[6];
            Integer[] audiogramChannelRight = new Integer[6];

            // NAL audiogram values need to be in range [0,120] dBHL
            // Aspen may venture outside of this range. According to docs we should
            // clamp the values.

            for (int i = 0; i < audiogramChannelLeft.length; i++) {
                Integer value = audiogram.getLeftChannel().get(i).intValue();

                if (value > 120) {
                    value = 120;
                } else if (value < 0) {
                    value = 0;
                }

                audiogramChannelLeft[i] = value;
            }

            for (int i = 0; i < audiogramChannelRight.length; i++) {
                Integer value = audiogram.getRightChannel().get(i).intValue();

                if (value > 120) {
                    value = 120;
                } else if (value < 0) {
                    value = 0;
                }

                audiogramChannelRight[i] = value;
            }

            // The NAL wrapper expects values for 9 frequencies:
            //      index   0    1     2    3     4     5      6    7     8
            //      freq  [250, 500, 1000, 1500, 2000, 3000, 4000, 6000, 8000]
            //
            // We only have 6 sampled frequencies: [250, 500, 1000, 2000, 4000, 8000]
            // Set 999 according to the NAL library on the ones that we don't have,
            Integer[] leftSamplesIntArray = new Integer[9];
            Integer[] rightSamplesIntArray = new Integer[9];

            // To make this abundantly clear, assign each value manually:
            // 250Hz
            leftSamplesIntArray[0] = audiogramChannelLeft[0];
            rightSamplesIntArray[0] = audiogramChannelRight[0];
            // 500Hz
            leftSamplesIntArray[1] = audiogramChannelLeft[1];
            rightSamplesIntArray[1] = audiogramChannelRight[1];
            // 1000Hz
            leftSamplesIntArray[2] = audiogramChannelLeft[2];
            rightSamplesIntArray[2] = audiogramChannelRight[2];
            // 1500Hz
            leftSamplesIntArray[3] = 999;
            rightSamplesIntArray[3] = 999;
            // 2000Hz
            leftSamplesIntArray[4] = audiogramChannelLeft[3];
            rightSamplesIntArray[4] = audiogramChannelRight[3];
            // 3000Hz
            leftSamplesIntArray[5] = 999;
            rightSamplesIntArray[5] = 999;
            // 4000Hz
            leftSamplesIntArray[6] = audiogramChannelLeft[4];
            rightSamplesIntArray[6] = audiogramChannelRight[4];
            // 6000Hz
            leftSamplesIntArray[7] = 999;
            rightSamplesIntArray[7] = 999;
            // 8000Hz
            leftSamplesIntArray[8] = audiogramChannelLeft[5];
            rightSamplesIntArray[8] = audiogramChannelRight[5];

            String nal_params_json = getNalNl2Config();

            if (nal_params_json.equals(""))
            {
                Log.e("AspenWrapper", "Attempt to activate NalNl2 on a device without config. Ignoring.");
                return;
            }

            java.util.Map<String, Object> nalConfigMap = new java.util.HashMap<>();
            nalConfigMap.put("hasExperience", nalNl2Data.hasExperience ? 0 : 1); // 0 - experienced 1 - no experience with hearing aids
            nalConfigMap.put("isTonal", nalNl2Data.isTonalLanguage ? 1 : 0); // 0 - non-tonal 1 - tonal
            nalConfigMap.put("gender", convertAspenGenderToNalNl2Gender(gender));
            nalConfigMap.put("leftSamples", leftSamplesIntArray);
            nalConfigMap.put("rightSamples", rightSamplesIntArray);
            nalConfigMap.put("nalParamsJson", nal_params_json);

            Map<String, double[][]> result = getCheckedResult(applicationContext, nalConfigMap);

            double[][] left_gain_matrix = result.get("left_gain_matrix");
            double[][] right_gain_matrix = result.get("right_gain_matrix");

            FloatMatrix left_float_matrix = convertToFloatMatrix(left_gain_matrix);
            FloatMatrix right_float_matrix = convertToFloatMatrix(right_gain_matrix);

            setTypeNalNl2(mode, left_float_matrix, right_float_matrix);
        } catch (Exception e) {
            Log.e("AspenWrapper", "Error occurred " + e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    private Map<String, double[][]> getCheckedResult(Context applicationContext, Map<String, Object> nalConfigMap) throws
           ClassNotFoundException, NoSuchMethodException, IllegalAccessException, InvocationTargetException {

        Class<?> aspenNAL = this.getClass().getClassLoader().loadClass("com.audiodo.aspennal.AspenNAL");
        Method getNalNl2Gains = aspenNAL.getMethod("getNAL_NL2_Gains", Context.class, java.util.Map.class);
        Map<String, double[][]> typedResult;
        Object resultObj = getNalNl2Gains.invoke(aspenNAL, applicationContext, nalConfigMap);

        if (resultObj instanceof Map) {
            Map<?, ?> resultMap = (Map<?, ?>) resultObj;
            boolean keysAreStrings = resultMap.keySet().stream().allMatch(key -> key instanceof String);
            boolean valuesAreDoubleArrays = resultMap.values().stream().allMatch(value -> value instanceof double[][]);

            if (keysAreStrings && valuesAreDoubleArrays) {
                // Now you can safely cast the map
                typedResult = (Map<String, double[][]>) resultObj;
            } else {
                throw new RuntimeException("The map keys are not Strings or the values are not double[][]");
            }
        } else {
            throw new RuntimeException("The result is not a Map");
        }
        return typedResult;
    }


  /**
   * Set Audiodo personalization transparency type<br>
   * <br>
   * An asynchronous request to set Audiodo personalization transparency type.<br>
   * <br>
   * It will use the profile to perform personal sound compensation<br>
   * on the transparency audio.<br>
   * <br>
   * When enabling Audiodo personalization, the gain ranges may update as there is typically<br>
   * a lower maximum gain allowance while a personalization is in effect. This may<br>
   * trigger a clamping of the set gain, which in turn will trigger a separate<br>
   * observable event. See the set_gain documentation for details on this event.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_set_type_audiodo_confirmation">get_observable_event_set_type_audiodo_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param mode The transparency mode to use<br>
   * @param profile_id The ID of the profile to use for personalization
   */
  public void setTypeAudiodo(AudiodoTransparencyMode mode, String profile_id) {
    AspenJNI.IAudiodoTransparencyCapability_setTypeAudiodo(swigCPtr, this, mode.swigValue(), profile_id);
  }

  /**
   * Set NAL-NL2 personalization transparency type<br>
   * <br>
   * An asynchronous request to set NAL-NL2 personalization transparency type.<br>
   * <br>
   * The matrix consists of gains - each calculated as a function of frequency and sound pressure.<br>
   * <br>
   * @param mode The transparency mode to use<br>
   * @param left_gain_matrix The NAL compensation matrix for the left ear.<br>
   * @param right_gain_matrix The NAL compensation matrix for the right ear.
   */
  private void setTypeNalNl2(AudiodoTransparencyMode mode, FloatMatrix left_gain_matrix, FloatMatrix right_gain_matrix) {
    AspenJNI.IAudiodoTransparencyCapability_setTypeNalNl2(swigCPtr, this, mode.swigValue(), FloatMatrix.getCPtr(left_gain_matrix), left_gain_matrix, FloatMatrix.getCPtr(right_gain_matrix), right_gain_matrix);
  }

  /**
   * Set Generic transparency type<br>
   * <br>
   * An asynchronous request to set Generic transparency type.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_set_type_generic_confirmation">get_observable_event_set_type_generic_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param mode The transparency mode to use
   */
  public void setTypeGeneric(AudiodoTransparencyMode mode) {
    AspenJNI.IAudiodoTransparencyCapability_setTypeGeneric(swigCPtr, this, mode.swigValue());
  }

  /**
   * Check if personalization is activated, i.e. transparency type is not Generic.<br>
   * <br>
   * @return True if it is activated, false if it is deactivated.
   */
  public boolean isPersonalizationActivated() {
    return AspenJNI.IAudiodoTransparencyCapability_isPersonalizationActivated(swigCPtr, this);
  }

  /**
   * Check if the AudiodoTransparencyType is supported.<br>
   * <br>
   * @return True if it is supported, false otherwise.
   */
  public boolean isTransparencyTypeSupported(AudiodoTransparencyType type) {
    if (type == AudiodoTransparencyType.NAL_NL2) {
        try {
            Class<?> aspenNAL = this.getClass().getClassLoader().loadClass("com.audiodo.aspennal.AspenNAL");
        } catch (ClassNotFoundException e) {
            return false;
        }
    }
    return AspenJNI.IAudiodoTransparencyCapability_isTransparencyTypeSupported(swigCPtr, this, type.swigValue());
}

  /**
   *  Get the currently active transparency type.<br>
   * <br>
   * @return AudiodoTransparencyType Returns the currently active transparency type.
   */
  public AudiodoTransparencyType getCurrentTransparencyType() {
    return AudiodoTransparencyType.swigToEnum(AspenJNI.IAudiodoTransparencyCapability_getCurrentTransparencyType(swigCPtr, this));
  }

  /**
   * Set a gain<br>
   * <br>
   * An asynchronous request to set a gain value in dB for the transparency. The<br>
   * value will be clamped between <a href="#get_min_gain">get_min_gain</a> and <a href="#get_max_gain">get_max_gain</a>.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_configure_confirmation">get_observable_event_configure_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param gain The gain value in dB, allowed range is from <a href="#get_min_gain">get_min_gain</a> to <a href="#get_max_gain">get_max_gain</a>
   */
  public void setGain(int gain) {
    AspenJNI.IAudiodoTransparencyCapability_setGain(swigCPtr, this, gain);
  }

  /**
   * Get the gain setting<br>
   * <br>
   * Note: Returns 0 if the device is not in sync yet.<br>
   * <br>
   * @return The gain value in dB
   */
  public int getGain() {
    return AspenJNI.IAudiodoTransparencyCapability_getGain(swigCPtr, this);
  }

  /**
   * Get the max gain<br>
   * <br>
   * @return The max gain value in dB
   */
  public int getMaxGain() {
    return AspenJNI.IAudiodoTransparencyCapability_getMaxGain(swigCPtr, this);
  }

  /**
   * Get the min gain<br>
   * <br>
   * @return The min gain value in dB
   */
  public int getMinGain() {
    return AspenJNI.IAudiodoTransparencyCapability_getMinGain(swigCPtr, this);
  }

  /**
   * Get the mode setting<br>
   * <br>
   * Note: Ensure device is in sync before using this API.<br>
   * <br>
   * @return The mode
   */
  public AudiodoTransparencyMode getMode() {
    return AudiodoTransparencyMode.swigToEnum(AspenJNI.IAudiodoTransparencyCapability_getMode(swigCPtr, this));
  }

  /**
   * Get the NAL-NL2 configuration<br>
   * <br>
   * Note: The configuration is a string and should be parsed as JSON<br>
   * <br>
   * @return The NAL-NL2 configuration
   */
  private String getNalNl2Config() {
    return AspenJNI.IAudiodoTransparencyCapability_getNalNl2Config(swigCPtr, this);
  }

  /**
   * Check if noise suppressor is active<br>
   * <br>
   * Note: Ensure device is in sync before using this API.<br>
   * <br>
   * @return True if it is activated, false otherwise
   */
  public boolean isNoiseSuppressorActivated() {
    return AspenJNI.IAudiodoTransparencyCapability_isNoiseSuppressorActivated(swigCPtr, this);
  }

  /**
   * Check if feedback suppression is active<br>
   * <br>
   * Note: Ensure device is in sync before using this API.<br>
   * <br>
   * @return True if it is activated, false otherwise
   */
  public boolean isFeedbackSuppressionActivated() {
    return AspenJNI.IAudiodoTransparencyCapability_isFeedbackSuppressionActivated(swigCPtr, this);
  }

  /**
   * Get the maximum noise reduction for the noise suppressor<br>
   * <br>
   * Note: Ensure device is in sync before using this API.<br>
   * <br>
   * @return maximum noise reduction in dB
   */
  public long getNoiseSuppressorMaxReduction() {
    return AspenJNI.IAudiodoTransparencyCapability_getNoiseSuppressorMaxReduction(swigCPtr, this);
  }

  /**
   * Get the feedback suppression mode<br>
   * <br>
   * Note: Ensure device is in sync before using this API.<br>
   * <br>
   * @return feedback suppression mode
   */
  public AudiodoTransparencyFeedbackSuppressionMode getFeedbackSuppressionMode() {
    return AudiodoTransparencyFeedbackSuppressionMode.swigToEnum(AspenJNI.IAudiodoTransparencyCapability_getFeedbackSuppressionMode(swigCPtr, this));
  }

  /**
   * Activate Feedback Suppression<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if feedback suppression was activated, false otherwise.
   */
  public boolean activateFeedbackSuppression() {
    return AspenJNI.IAudiodoTransparencyCapability_activateFeedbackSuppression(swigCPtr, this);
  }

  /**
   * Deactivate Feedback Suppression<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if feedback suppression was deactivated, false otherwise.
   */
  public boolean deactivateFeedbackSuppression() {
    return AspenJNI.IAudiodoTransparencyCapability_deactivateFeedbackSuppression(swigCPtr, this);
  }

  /**
   * Activate Noise Suppressor<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if noise suppressor was activated, false otherwise.
   */
  public boolean activateNoiseSuppressor() {
    return AspenJNI.IAudiodoTransparencyCapability_activateNoiseSuppressor(swigCPtr, this);
  }

  /**
   * Deactivate Noise Suppressor<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if noise suppressor was deactivated, false otherwise.
   */
  public boolean deactivateNoiseSuppressor() {
    return AspenJNI.IAudiodoTransparencyCapability_deactivateNoiseSuppressor(swigCPtr, this);
  }

  /**
   * Set max noise reduction<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * @param value the max noise reduction in dB<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if max noise reduction was successfully updated, false otherwise.
   */
  public boolean setMaxNoiseReduction(long value) {
    return AspenJNI.IAudiodoTransparencyCapability_setMaxNoiseReduction(swigCPtr, this, value);
  }

  /**
   * Set Feedback Suppression Mode<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * @param mode The mode to set<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * Note: Changing the transparency type with a new mode will automatically update this parameter<br>
   * back to the default value for that specific mode.<br>
   * <br>
   * @return True if feedback suppression mode was successfully updated, false otherwise.
   */
  public boolean setFeedbackSuppressionMode(AudiodoTransparencyFeedbackSuppressionMode mode) {
    return AspenJNI.IAudiodoTransparencyCapability_setFeedbackSuppressionMode(swigCPtr, this, mode.swigValue());
  }

  /**
   * Check if the device supports locking noise suppression value to the gain<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Use this method to check if the device supports locking the noise suppression value to the gain value.<br>
   * <br>
   * @return True if device supports locking the noise suppression configuration to the gain, false otherwise.
   */
  public boolean isNoiseSuppressionLockedToGainSupported() {
    return AspenJNI.IAudiodoTransparencyCapability_isNoiseSuppressionLockedToGainSupported(swigCPtr, this);
  }

  /**
   * Lock and unlock the noise suppression value to the gain<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * Use this method to lock and unlock the noise suppression value to the gain. When locked the noise<br>
   * suppression value will change automatically when the gain is changed according to the following table:<br>
   * <br>
   *    Gain   | Noise Suppression<br>
   * --------- | -----------------<br>
   *    -12    |        2<br>
   *  -11..-9  |        3<br>
   *   -8..-6  |        4<br>
   *   -5..-3  |        5<br>
   *   -2..2   |        6<br>
   *    3..5   |        7<br>
   *    6..8   |        8<br>
   *    9..11  |        9<br>
   *   12..25  |       10<br>
   * <br>
   * @return True if the noise suppression was locked to the gain, False otherwise
   */
  public boolean setIsNoiseSuppressionLockedToGain(boolean lock) {
    return AspenJNI.IAudiodoTransparencyCapability_setIsNoiseSuppressionLockedToGain(swigCPtr, this, lock);
  }

  /**
   * Check if the noise suppression value is currently being locked to the gain<br>
   * <br>
   * Note: This function requires a license. If there is no license, the function will return false.<br>
   * <br>
   * @return True if the noise suppression is currently being locked to the gain, false otherwise.
   */
  public boolean isNoiseSuppressionLockedToGain() {
    return AspenJNI.IAudiodoTransparencyCapability_isNoiseSuppressionLockedToGain(swigCPtr, this);
  }

  /**
   * Resets the extra API back to the default configuration<br>
   * <br>
   * The extra apis include toggling noise_suppressor, toggling feedback_suppression, set max noise<br>
   * reduction and set feedback suppression mode.<br>
   * <br>
   * Observers will be notified with multiple events of type <a href="#get_observable_event_extra_api_set_confirmation">get_observable_event_extra_api_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @return True if it was successfully reset, false otherwise.
   */
  public boolean resetExtraApis() {
    return AspenJNI.IAudiodoTransparencyCapability_resetExtraApis(swigCPtr, this);
  }

  /**
   * Reset the transparency config<br>
   * <br>
   * Note: Requires an active session with an audio device.<br>
   * <br>
   * Resets the transparency configuration to its default values.<br>
   * Observers will be notified with event <a href="#get_observable_event_configure_confirmation">get_observable_event_configure_confirmation</a> if any changes<br>
   * occurred.<br>
   * <br>
   * @param resetPersonalization If true, the personalization setting is also reset to generic, otherwise<br>
   *                             it is left as is.<br>
   * @return True if configuration was successfully reset, false otherwise.
   */
  public boolean reset(boolean resetPersonalization) {
    return AspenJNI.IAudiodoTransparencyCapability_reset(swigCPtr, this, resetPersonalization);
  }

  /**
   * Check if the capability is in sync with the audio device.<br>
   * <br>
   * @return True if it is in sync, false if not in sync.
   */
  public boolean remoteDeviceInSync() {
    return AspenJNI.IAudiodoTransparencyCapability_remoteDeviceInSync(swigCPtr, this);
  }

  /**
   *  Notification that the capability is in sync with device<br>
   * <br>
   * On session establish the transparency capability will synchronize with the remote<br>
   * device. On completion the observers will be notified with this event. The subject<br>
   * parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSyncComplete() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSyncComplete();
  }

  /**
   *  Confirmation from device that the Audiodo personalization transparency type has been set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_type_audiodo">set_type_audiodo</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetTypeAudiodoConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSetTypeAudiodoConfirmation();
  }

  /**
   *  Confirmation from device that the Generic transparency type has been set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_type_generic">set_type_generic</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetTypeGenericConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSetTypeGenericConfirmation();
  }

  /**
   *  Confirmation from device that the a configuration was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_gain">set_gain</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventConfigureConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventConfigureConfirmation();
  }

  /**
   *  Confirmation for a configuration set using the extra apis<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventExtraApiSetConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventExtraApiSetConfirmation();
  }

  /**
   *  Confirmation from device that the NAL-NL2 personalization transparency type has been set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_type_nal_nl2">set_type_nal_nl2</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetTypeNalNl2Confirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSetTypeNalNl2Confirmation();
  }

  /**
   *  NOT TO BE USED FOR ANYTHING OTHER THAN LAB TESTS FOR ANSI3.22:2014<br>
   * <br>
   * Confirmation from device that the ANSI3.22:2014 FOG transparency type has been set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_type_ansi3_22_2014_fog">set_type_ansi3_22_2014_fog</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetTypeAnsi3222014FogConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSetTypeAnsi3222014FogConfirmation();
  }

  /**
   *  NOT TO BE USED FOR ANYTHING OTHER THAN LAB TESTS FOR ANSI3.22:2014<br>
   * <br>
   * Confirmation from device that the ANSI3.22:2014 RTS transparency type has been set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_type_ansi3_22_2014_rts">set_type_ansi3_22_2014_rts</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetTypeAnsi3222014RtsConfirmation() {
    return AspenJNI.IAudiodoTransparencyCapability_getObservableEventSetTypeAnsi3222014RtsConfirmation();
  }

}
