/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class IAudiosphereIrCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IAudiosphereIrCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IAudiosphereIrCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAudiosphereIrCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IAudiosphereIrCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Activate audiosphere IR<br>
   * <br>
   * An asynchronous request to activate audiosphere IR. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_confirmation">get_observable_event_activate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void activate() {
    AspenJNI.IAudiosphereIrCapability_activate(swigCPtr, this);
  }

  /**
   * Deactivate audiosphere IR<br>
   * <br>
   * An asynchronous request to deactivate audiosphere IR. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_confirmation">get_observable_event_deactivate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivate() {
    AspenJNI.IAudiosphereIrCapability_deactivate(swigCPtr, this);
  }

  /**
   * Check if the audiosphere IR is active<br>
   * <br>
   * @return True if it is active, false if inactive.
   */
  public boolean isActive() {
    return AspenJNI.IAudiosphereIrCapability_isActive(swigCPtr, this);
  }

  /**
   * Set a configuration for the audiosphere IR<br>
   * <br>
   * An asynchronous request to set a new audiosphere IR configuration.<br>
   * Observers will be notified with event <a href="#get_observable_event_set_confirmation">get_observable_event_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param config Configuration to apply.
   */
  public void setConfig(AudiosphereIrConfig config) {
    AspenJNI.IAudiosphereIrCapability_setConfig(swigCPtr, this, AudiosphereIrConfig.getCPtr(config), config);
  }

  /**
   * Get a copy of the configuration object<br>
   * <br>
   * Please note that this is only a copy of the configuration. Any changes to it must be<br>
   * applied by calling <a href="#set_config">set_config</a>.<br>
   * <br>
   * @return The AudiosphereIrConfig object
   */
  public AudiosphereIrConfig getConfig() {
    return new AudiosphereIrConfig(AspenJNI.IAudiosphereIrCapability_getConfig(swigCPtr, this), true);
  }

  /**
   *  Confirmation from device that audiosphere IR has been activated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate">activate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateConfirmation() {
    return AspenJNI.IAudiosphereIrCapability_getObservableEventActivateConfirmation();
  }

  /**
   *  Confirmation from device that audiosphere IR has been deactivated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate">deactivate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateConfirmation() {
    return AspenJNI.IAudiosphereIrCapability_getObservableEventDeactivateConfirmation();
  }

  /**
   *  Confirmation from device that audiosphere IR configuration was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_config">set_config</a>. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetConfirmation() {
    return AspenJNI.IAudiosphereIrCapability_getObservableEventSetConfirmation();
  }

}
