/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The Bass Boost capability<br>
 * <br>
 * This class is an interface to the bass boost capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to perform actions on the bass boost.
 */
public class IBassBoostCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IBassBoostCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IBassBoostCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IBassBoostCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IBassBoostCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Activate the bass boost.<br>
   * <br>
   * An asynchronous request to activate the bass boost. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_confirmation">get_observable_event_activate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void activate() {
    AspenJNI.IBassBoostCapability_activate(swigCPtr, this);
  }

  /**
   * Deactivate the bass boost.<br>
   * <br>
   * An asynchronous request to deactivate the bass boost. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_confirmation">get_observable_event_deactivate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivate() {
    AspenJNI.IBassBoostCapability_deactivate(swigCPtr, this);
  }

  /**
   * Set the bass boost strength percent<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_set_confirmation">get_observable_event_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param strength_percent The bass boost strength percent to set.
   */
  public void setStrengthPercent(short strength_percent) {
    AspenJNI.IBassBoostCapability_setStrengthPercent(swigCPtr, this, strength_percent);
  }

  /**
   * Check if the bass boost is activated.<br>
   * <br>
   * @return True if it is activated, false if it is deactivated.
   */
  public boolean isActivated() {
    return AspenJNI.IBassBoostCapability_isActivated(swigCPtr, this);
  }

  /**
   * Get the bass boost strength percent<br>
   * <br>
   * @return The bass boost strength percent
   */
  public short getStrengthPercent() {
    return AspenJNI.IBassBoostCapability_getStrengthPercent(swigCPtr, this);
  }

  /**
   *  Confirmation from device that the bass boost is activated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate">activate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateConfirmation() {
    return AspenJNI.IBassBoostCapability_getObservableEventActivateConfirmation();
  }

  /**
   *  Confirmation from device that the bass boost is deactivated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate">deactivate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateConfirmation() {
    return AspenJNI.IBassBoostCapability_getObservableEventDeactivateConfirmation();
  }

  /**
   *  Confirmation from device that the bass boost strength percent was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_strength_percent">set_strength_percent</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetConfirmation() {
    return AspenJNI.IBassBoostCapability_getObservableEventSetConfirmation();
  }

}
