/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 *  The battery capability<br>
 * <br>
 * This class is an interface to the battery capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to get the battery level of the remote audio device. The user of this capability will<br>
 * need to request battery level on an appropriate period. The latest level seen is available through the api.
 */
public class IBatteryCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IBatteryCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IBatteryCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IBatteryCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IBatteryCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Request a battery level update<br>
   * <br>
   * This method is used to request a new battery level update.<br>
   * A notification will arrive via <a href="#IPropertyObserver">IPropertyObserver</a> registered in this capability<br>
   * when a new level is available.
   */
  public void requestBatteryLevel() {
    AspenJNI.IBatteryCapability_requestBatteryLevel(swigCPtr, this);
  }

  /**
   *  Get the latest battery level<br>
   * <br>
   * Get the latest battery level received from a request. Request an update with<br>
   * "request_battery_level". For tws devices there will be two levels available.<br>
   * For headset devices there will be one. Each entry is an integer representing<br>
   * battery percentage level. If return value is -1, the data is not available.<br>
   * <br>
   * @return A vector of battery levels in percent.
   */
  public IntVector getLevel() {
    return new IntVector(AspenJNI.IBatteryCapability_getLevel(swigCPtr, this), true);
  }

  /**
   *  The event for battery level<br>
   * <br>
   * When the battery level has changed this event will be sent.<br>
   * <br>
   * This method can be used to get the string constant that notifies that<br>
   * a new battery level is available.<br>
   * To be used in the <a href="#IPropertyObserver">IPropertyObserver</a> property_changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventBatteryLevel() {
    return AspenJNI.IBatteryCapability_getObservableEventBatteryLevel();
  }

}
