/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;
import androidx.annotation.Nullable;
/**
 *  The CalibrationCapability<br>
 * <br>
 * This class is an interface to the calibration capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * Through it a user may run a calibration and get a calibration result.
 */
public class ICalibrationCapability {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ICalibrationCapability(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICalibrationCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ICalibrationCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
  private ICalibrationCapabilityCallbacks callbackReference;
  /**
   * Starts a new calibration<br>
   * <br>
   * Any calibration previously in progress will be overwritten and a new one<br>
   * will commence. The first tone will start playing as soon as possible and<br>
   * will be signaled by a "tone_playing" callback.<br>
   * <br>
   * @param cbs A pointer to an implemented ICalibrationCapabilityCallbacks class<br>
   * <br>
   * @return bool Returns true if calibration was successfully started, false if not.
   */
  public boolean start(ICalibrationCapabilityCallbacks cbs) {
    try {
      return AspenJNI.ICalibrationCapability_start(swigCPtr, this, ICalibrationCapabilityCallbacks.getCPtr(cbs), cbs);
    } finally {
      callbackReference = cbs;
    }
  }

  /**
   * Stops a calibration<br>
   * <br>
   * Stops an ongoing calibration. This should be called in all circumstances when<br>
   * leaving the calibration for any reason except a completed calibration. Else<br>
   * tone generation will commence in the audio device. If a calibration is not in<br>
   * progress a call to this method will be ignored.
   */
  public void stop() {
    AspenJNI.ICalibrationCapability_stop(swigCPtr, this);
    callbackReference = null;
  }

  /**
   * Called when a user pressed yes<br>
   * <br>
   * Updates the calibration runner with the information that the user pressed yes.<br>
   * "tone_not_playing"-callback will be called when the tone has stopped playing.
   */
  public void userPressedYes() {
    AspenJNI.ICalibrationCapability_userPressedYes(swigCPtr, this);
  }

  /**
   * Called when a user pressed no<br>
   * <br>
   * Updates the calibration runner with the information that the user pressed no.<br>
   * "tone_not_playing"-callback will be called when the tone has stopped playing.
   */
  public void userPressedNo() {
    AspenJNI.ICalibrationCapability_userPressedNo(swigCPtr, this);
  }

  /**
   * Get calibration progress<br>
   * <br>
   * @return A value representing the progress in percent
   */
  public long getProgress() {
    return AspenJNI.ICalibrationCapability_getProgress(swigCPtr, this);
  }

  /**
   * Get detailed calibration progress data<br>
   * <br>
   * The function can be used to get more detailed information regarding the<br>
   * progress of a calibration. The calibration is performed by playing<br>
   * a certain number of intensities for each frequency. For each channel<br>
   * a certain number of frequencies are played. E.g. five intensities across<br>
   * six frequencies. This is repeated for two channels.<br>
   * <br>
   * @return A CalibrationCapabilityProgressData object containing detailed<br>
   *         data of the progress or NULL if there is no calibration in progress or<br>
   *         no calibration has been completed.
   */
  @Nullable
  public CalibrationCapabilityProgressData getProgressData() {
    long cPtr = AspenJNI.ICalibrationCapability_getProgressData(swigCPtr, this);
    return (cPtr == 0) ? null : new CalibrationCapabilityProgressData(cPtr, true);
}

  /**
   * Returns the calibration result<br>
   * <br>
   * Returns a result if a calibration has been completed. If not it will return nullptr.<br>
   * Result will be kept until a new calibration is started.<br>
   * <br>
   * @return A pointer to the calibration result, or nullptr if calibration is not complete
   */
  @Nullable
  public ICalibrationResult getResult() {
    long cPtr = AspenJNI.ICalibrationCapability_getResult(swigCPtr, this);
    return (cPtr == 0) ? null : new ICalibrationResult(cPtr, true);
  }

  /**
   * Resume an interrupted calibration<br>
   * <br>
   * Resumes an interrupted calibration if everything is OK again. If<br>
   * the calibration has been paused for more than 60 seconds the<br>
   * calibration will be stopped and the aborted callback will be<br>
   * called.<br>
   * <br>
   * @return True if calibration was able to be resumed, false if it was<br>
   *         not able to be resumed.
   */
  public boolean resume() {
    return AspenJNI.ICalibrationCapability_resume(swigCPtr, this);
  }

  /**
   * Get the current status of the calibration<br>
   * <br>
   * @return The current status of the calibration capability.
   */
  public CalibrationCapabilityStatus getStatus() {
    return CalibrationCapabilityStatus.swigToEnum(AspenJNI.ICalibrationCapability_getStatus(swigCPtr, this));
  }

  /**
   * Pause the ongoing calibration<br>
   * <br>
   * Pause the ongoing calibration. On resume the calibration will<br>
   * restart from the beginning of the current frequency. The<br>
   * calibration is only allowed to be paused for up to 60 seconds. If<br>
   * its paused any longer the resume call will fail.
   */
  public void pause() {
    AspenJNI.ICalibrationCapability_pause(swigCPtr, this);
  }

  /**
   * Get a vector with the frequencies used in the calibration.<br>
   * <br>
   * @return std::vector&lt;uint16_t&gt; Returns a vector with the frequencies used in the calibration.
   */
  public UintVector getFrequencies() {
    return new UintVector(AspenJNI.ICalibrationCapability_getFrequencies(swigCPtr, this), true);
  }

  /**
   * Restart frequency test<br>
   * <br>
   * This function allows a user to restart the test of a frequency.<br>
   * It is only possible to restart on a frequency, not on a specific tone.<br>
   * By tone is meant a frequency with an amplitude.<br>
   * Which frequency that is restarted depends on the current progress:<br>
   *  - If playing the second tone or more, the current frequency is restarted<br>
   *  - If playing the first tone of a frequency, the previous frequency is restarted<br>
   *  - If playing the first tone of a frequency on the second ear, the last frequency<br>
   *    on the previous ear is restarted<br>
   * <br>
   * It is not possible to restart the frequency when playing the first tone on the first<br>
   * frequency on first ear.<br>
   * The user can restart the previous frequency until the first frequency on first ear.<br>
   * <br>
   * @return True if successful, false otherwise
   */
  public boolean restartFrequency() {
    return AspenJNI.ICalibrationCapability_restartFrequency(swigCPtr, this);
  }

}
