/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public abstract class ICalibrationCapabilityCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ICalibrationCapabilityCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICalibrationCapabilityCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ICalibrationCapabilityCallbacks obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ICalibrationCapabilityCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AspenJNI.ICalibrationCapabilityCallbacks_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AspenJNI.ICalibrationCapabilityCallbacks_change_ownership(this, swigCPtr, true);
  }

  /**
   * Signals that a tone is playing and contains progress data<br>
   * <br>
   * Signals that a tone is playing in the audio device. It also contains<br>
   * data of the progress of the calibration.
   */
  public abstract void tonePlaying(CalibrationCapabilityProgressData progress) ;

  /**
   * Signals that a tone has stopped playing<br>
   * <br>
   * Signals that a tone has stopped playing in the audio device.<br>
   * This should stop any animation or similar.
   */
  public abstract void toneNotPlaying() ;

  /**
   * Signals that a frequency is complete<br>
   * <br>
   * Signals that a frequency is now complete. Any animation to<br>
   * inform user that the calibration will change to a new frequency<br>
   * should be done now.
   */
  public abstract void frequencyComplete() ;

  /**
   * Signals that a channel is complete<br>
   * <br>
   * Signals that a channel is now complete. Any animation to inform<br>
   * user that the calibration will continue on the other ear should be<br>
   * done now.
   */
  public abstract void channelComplete() ;

  /**
   * Signals that the calibration is complete<br>
   * <br>
   * Signals that the calibration is complete. A result is now available<br>
   * by calling get_result().
   */
  public abstract void calibrationComplete() ;

  /**
   * Signals that the calibration has been aborted.<br>
   * <br>
   * Signals that the calibration has been aborted by the audio device. One<br>
   * cause could be an incoming call. The calibration will have to be restarted<br>
   * when the interruption has passed.<br>
   * <br>
   * @param reason The reason why the calibration was aborted
   */
  public abstract void aborted(CalibrationCapabilityAbortReason reason) ;

  /**
   * Signals that the calibration has been interrupted due to a peer disconnect.<br>
   * <br>
   * Signals that the calibration has been interrupted as the peer earbud has disconnected.<br>
   * Reconnect the peer to be able to resume calibration.
   */
  public abstract void interruptedPeerDisconnected() ;

  /**
   * Signals that the peer has been connected.
   */
  public abstract void peerConnected() ;

  /**
   * Signals that the calibration is busy tearing down the previous calibration.
   */
  public abstract void calibrationDowntime() ;

  public ICalibrationCapabilityCallbacks() {
    this(AspenJNI.new_ICalibrationCapabilityCallbacks(), true);
    AspenJNI.ICalibrationCapabilityCallbacks_director_connect(this, swigCPtr, true, true);
  }

}
