/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 *  CalibrationResult<br>
 * <br>
 * A handle to a calibration result. This class is a methodless interface to a CalibrationResult within<br>
 * Aspen. Used to create a profile.
 */
public class ICalibrationResult {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ICalibrationResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICalibrationResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ICalibrationResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ICalibrationResult() {
    this(AspenJNI.new_ICalibrationResult(), true);
  }

}
