/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The Detail enhancer capability<br>
 * <br>
 * This class is an interface to the detail enhancer capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to perform actions on the detail enhancer.
 */
public class IDetailEnhancerCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IDetailEnhancerCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IDetailEnhancerCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDetailEnhancerCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IDetailEnhancerCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Activate the detail enhancer.<br>
   * <br>
   * An asynchronous request to activate the detail enhancer. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_confirmation">get_observable_event_activate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void activate() {
    AspenJNI.IDetailEnhancerCapability_activate(swigCPtr, this);
  }

  /**
   * Deactivate the detail enhancer.<br>
   * <br>
   * An asynchronous request to deactivate the detail enhancer. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_confirmation">get_observable_event_deactivate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivate() {
    AspenJNI.IDetailEnhancerCapability_deactivate(swigCPtr, this);
  }

  /**
   * Set the detail enhancer effect percent<br>
   * <br>
   * Observers will be notified with event <a href="#get_observable_event_set_confirmation">get_observable_event_set_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param effect_percent The detail enhancer effect percent to set.
   */
  public void setEffectPercent(short effect_percent) {
    AspenJNI.IDetailEnhancerCapability_setEffectPercent(swigCPtr, this, effect_percent);
  }

  /**
   * Check if the detail enhancer is activated.<br>
   * <br>
   * @return True if it is activated, false if it is deactivated.
   */
  public boolean isActivated() {
    return AspenJNI.IDetailEnhancerCapability_isActivated(swigCPtr, this);
  }

  /**
   * Get the detail enhancer effect percent<br>
   * <br>
   * @return The detail enhancer effect percent
   */
  public short getEffectPercent() {
    return AspenJNI.IDetailEnhancerCapability_getEffectPercent(swigCPtr, this);
  }

  /**
   *  Confirmation from device that the detail enhancer is activated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate">activate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateConfirmation() {
    return AspenJNI.IDetailEnhancerCapability_getObservableEventActivateConfirmation();
  }

  /**
   *  Confirmation from device that the detail enhancer is deactivated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate">deactivate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateConfirmation() {
    return AspenJNI.IDetailEnhancerCapability_getObservableEventDeactivateConfirmation();
  }

  /**
   *  Confirmation from device that the detail enhancer effect percent was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_effect_percent">set_effect_percent</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetConfirmation() {
    return AspenJNI.IDetailEnhancerCapability_getObservableEventSetConfirmation();
  }

}
