/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 *  The device info capability<br>
 * <br>
 * This class is an interface to the device info capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to get the device information from the audio device.
 */
public class IDeviceInfoCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IDeviceInfoCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IDeviceInfoCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDeviceInfoCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IDeviceInfoCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the type of volume representation<br>
   * <br>
   * Get the type of volume representation received when calling<br>
   * get_volume_level()<br>
   * <br>
   * @return Returns the type UNKNOWN, DBFS or INDEX
   */
  public IDeviceInfoCapability.VolumeType getVolumeType() {
    return IDeviceInfoCapability.VolumeType.swigToEnum(AspenJNI.IDeviceInfoCapability_getVolumeType(swigCPtr, this));
  }

  /**
   * Get the latest reported volume of the device<br>
   * <br>
   * Get the type of volume representation by calling<br>
   * get_volume_type().<br>
   * <br>
   * If type is unknown, this API will return 0<br>
   * <br>
   * @return Returns the volume
   */
  public byte getVolumeLevel() {
    return AspenJNI.IDeviceInfoCapability_getVolumeLevel(swigCPtr, this);
  }

  /**
   * Getter for the DeviceType type for this device service<br>
   * <br>
   * @return A device type signifying whether the device is headset or earbuds.
   */
  public DeviceType getDeviceType() {
    return DeviceType.swigToEnum(AspenJNI.IDeviceInfoCapability_getDeviceType(swigCPtr, this));
  }

  /**
   * Get the device build info string<br>
   * <br>
   * @return A string containing build info for the device.
   */
  public String getBuildInfo() {
    return AspenJNI.IDeviceInfoCapability_getBuildInfo(swigCPtr, this);
  }

  /**
   *  The event for volume level<br>
   * <br>
   * When the volume level has changed this event will be sent.<br>
   * <br>
   * This method can be used to get the string constant that notifies that<br>
   * a new volume level is available.<br>
   * To be used in the <a href="#IPropertyObserver">IPropertyObserver</a> property_changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventVolumeLevel() {
    return AspenJNI.IDeviceInfoCapability_getObservableEventVolumeLevel();
  }

  public enum VolumeType {
    UNKNOWN,
    DBFS,
    INDEX;

    public final int swigValue() {
      return swigValue;
    }

    public static VolumeType swigToEnum(int swigValue) {
      VolumeType[] swigValues = VolumeType.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (VolumeType swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + VolumeType.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private VolumeType() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private VolumeType(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private VolumeType(VolumeType swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
