/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 *  IDeviceServiceCallbacks interface<br>
 * <br>
 * This class is an abstract class that the integrator needs to inherit and override.<br>
 * It contains callbacks used by the <a href="#DeviceService">DeviceService</a> that is used for the duration of<br>
 * the transport session. The duration of the transport session starts by calling<br>
 * connect and ends when calling disconnect.
 */
public abstract class IDeviceServiceCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IDeviceServiceCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDeviceServiceCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IDeviceServiceCallbacks obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IDeviceServiceCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AspenJNI.IDeviceServiceCallbacks_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AspenJNI.IDeviceServiceCallbacks_change_ownership(this, swigCPtr, true);
  }

  /**
   * Tx send callback called when Aspen wants to send data<br>
   * <br>
   * Callback called by Aspen when a DeviceService wants to send data<br>
   * to its audio device counterpart. This method is expected to return<br>
   * immediately and should not block. Sending of the data need to take place<br>
   * in another context. The bytes passed here can't be fragmented. Any<br>
   * mtu requirements need to be passed when connecting the transport.<br>
   * <br>
   * @param bytes The bytes that are to be sent.
   */
  public abstract void send(Uint8Vector bytes) ;

  /**
   * A session has been established between a DeviceService and an audio device<br>
   * <br>
   * Called after "on_transport_connect" has been called for a new transport. A session has<br>
   * been established over the transport with the initial sync between the two partners done.<br>
   * <br>
   * The capabilities on the DeviceService is now ready to be used.
   */
  public abstract void sessionEstablished() ;

  /**
   * A session has been terminated<br>
   * <br>
   * Called when the DeviceService has terminated a session due to a cause specified in the<br>
   * supplied argument. This will release any callbacks and set the DeviceService in a state matching<br>
   * that of when on_transport_disconnect is called.<br>
   * <br>
   * @param cause The cause of the termination
   */
  public abstract void sessionTerminated(IDeviceServiceCallbacks.SessionTerminationCause cause) ;

  public IDeviceServiceCallbacks() {
    this(AspenJNI.new_IDeviceServiceCallbacks(), true);
    AspenJNI.IDeviceServiceCallbacks_director_connect(this, swigCPtr, true, true);
  }

  /**
   * Causes for session termination
   */
  public enum SessionTerminationCause {
    /**
     *  Device returned an error to the latest communication 
     */
    COMMUNICATION_ERROR,
    /**
     *  Communication timed out. Device took too long time to respond. 
     */
    COMMUNICATION_TIMEOUT,
    /**
     *  The device did not accept our authorization keys.<br>
     *    This is not recoverable, something is wrong in the configuration. 
     */
    AUTHORIZATION_DENIED,
    /**
     *  Authorization timed out. Device took too long to respond. 
     */
    AUTHORIZATION_TIMEOUT,
    /**
     *  The device has powered off. This will close the connection 
     */
    DEVICE_POWERED_OFF,
    /**
     *  A new client has connected. Close the current connection. 
     */
    NEW_CLIENT_CONNECTED,
    /**
     *  TWS buds are switching roles, terminate session 
     */
    TWS_ROLE_HANDOVER,
    /**
     *  Protocol version of device is higher than that of client. 
     */
    PROTOCOL_VERSION_NOT_SUPPORTED,
    /**
     *  Received model id from audio device does not match with created device. 
     */
    MODEL_ID_MISMATCH,
    /**
     *  Audio device's supported features does not match between sessions
     */
    ON_FEATURE_MISMATCH,
    /**
     *  Session was closed by client 
     */
    SESSION_CLOSED_BY_CLIENT;

    public final int swigValue() {
      return swigValue;
    }

    public static SessionTerminationCause swigToEnum(int swigValue) {
      SessionTerminationCause[] swigValues = SessionTerminationCause.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (SessionTerminationCause swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + SessionTerminationCause.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private SessionTerminationCause() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private SessionTerminationCause(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private SessionTerminationCause(SessionTerminationCause swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
