/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;
import androidx.annotation.Nullable;
/**
 * The DeviceService<br>
 * <br>
 * This class is the DeviceService, providing access to capabilities that can be interacted with<br>
 * on an audio device. It also provides the transport layer interface to enable communication<br>
 * over a transport defined by the user of this class.
 */
public class IDeviceService {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IDeviceService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDeviceService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IDeviceService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
  private IDeviceServiceCallbacks callbackReference;
  /**
   * Called when a transport is successfully connected and available to Aspen<br>
   * <br>
   * Informs Aspen that a new transport connection is setup and available to<br>
   * facilitate communication. Any mtu requirements need to be passed here to inform<br>
   * Aspen about how to fragment the data. In case any further fragmentation take place<br>
   * in lower layers of communication this needs to be reassembled before passed to<br>
   * the Audiodo rx counter part on the firmware device.<br>
   * <br>
   * @param cbs A reference to a ITransportSessionCallbacks implementation over which the<br>
   *             TransportManager will communicate.<br>
   * <br>
   * @param mtu The mtu (maximum transmission unit) allowed for the transport, i.e. the<br>
   *             maximum size allowed for a frame of bytes passed with the tx_send callback.<br>
   *             The minimum mtu value is 2.
   */
  public void onTransportConnect(IDeviceServiceCallbacks cbs, long mtu) {
    try {
      AspenJNI.IDeviceService_onTransportConnect(swigCPtr, this, IDeviceServiceCallbacks.getCPtr(cbs), cbs, mtu);
    } finally {
      callbackReference = cbs;
    }
  }

  /**
   * Called when a transport is disconnected.<br>
   * <br>
   * Informs Aspen that a transport connection has terminated. This will trigger teardown<br>
   * and handling of outstanding data within Aspen. Once a new connection is established it<br>
   * will need to be setup by calling on_transport_connect once more.
   */
  public void onTransportDisconnect() {
    AspenJNI.IDeviceService_onTransportDisconnect(swigCPtr, this);
    callbackReference = null;
  }

  /**
   * Called when rx data arrives over the connected transport to an audio device.<br>
   * <br>
   * Passes received rx data to a connected transport manager. If a connection is not setup when<br>
   * this is called nothing will happen and an error will be logged.<br>
   * Aspen will not modify this data, but read and parse it.<br>
   * <br>
   * @param bytes The bytes to be passed to Aspen.
   */
  public void onRx(Uint8Vector bytes) {
    AspenJNI.IDeviceService_onRx(swigCPtr, this, Uint8Vector.getCPtr(bytes), bytes);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#ICalibrationCapability">ICalibrationCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_calibration_capability_supported">is_calibration_capability_supported</a>.<br>
   * <br>
   * @return True when the device service has a calibration capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsCalibrationCapability() {
    return AspenJNI.IDeviceService_supportsCalibrationCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#ICalibrationCapability">ICalibrationCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#ICalibrationCapability">ICalibrationCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#ICalibrationCapability">ICalibrationCapability</a>.
   */
  public CapabilitySupportStatus isCalibrationCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isCalibrationCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#ICalibrationCapability">ICalibrationCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the calibration capability to be used for running calibrations.<br>
   * If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned. Actions on a calibration capability that affects the remote<br>
   * audio device will not be possible if the service does not have a session to it. Calls<br>
   * to such methods while a session is not established will be ignored.<br>
   * <br>
   * @return A pointer to the calibration capability, or nullptr if not supported.
   */
  @Nullable
  public ICalibrationCapability getCalibrationCapability() {
    long cPtr = AspenJNI.IDeviceService_getCalibrationCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new ICalibrationCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#IProfileCapability">IProfileCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_profile_capability_supported">is_profile_capability_supported</a>.<br>
   * <br>
   * @return True when device service has a profile capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsProfileCapability() {
    return AspenJNI.IDeviceService_supportsProfileCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IProfileCapability">IProfileCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IProfileCapability">IProfileCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IProfileCapability">IProfileCapability</a>.
   */
  public CapabilitySupportStatus isProfileCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isProfileCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IProfileCapability">IProfileCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the profile capability to be used for e.g. activating and<br>
   * deactivating profiles on a device.<br>
   * If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned. Actions on a profile capability that affects the remote<br>
   * audio device will not be possible if the service does not have a session to it. Calls<br>
   * to such methods while a session is not established will be ignored.<br>
   * <br>
   * @return A pointer to the profile capability, or nullptr if not supported.
   */
  @Nullable
  public IProfileCapability getProfileCapability() {
    long cPtr = AspenJNI.IDeviceService_getProfileCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IProfileCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#IBatteryCapability">IBatteryCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_battery_capability_supported">is_battery_capability_supported</a>.<br>
   * <br>
   * @return True when device service has a battery capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsBatteryCapability() {
    return AspenJNI.IDeviceService_supportsBatteryCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IBatteryCapability">IBatteryCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IBatteryCapability">IBatteryCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IBatteryCapability">IBatteryCapability</a>.
   */
  public CapabilitySupportStatus isBatteryCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isBatteryCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IBatteryCapability">IBatteryCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the battery capability to be used for getting battery level.<br>
   * If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the battery capability, or nullptr if not supported.
   */
  @Nullable
  public IBatteryCapability getBatteryCapability() {
    long cPtr = AspenJNI.IDeviceService_getBatteryCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IBatteryCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#IAncCapability">IAncCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_anc_capability_supported">is_anc_capability_supported</a>.<br>
   * <br>
   * @return True when device service has an ANC capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsAncCapability() {
    return AspenJNI.IDeviceService_supportsAncCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IAncCapability">IAncCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IAncCapability">IAncCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IAncCapability">IAncCapability</a>.
   */
  public CapabilitySupportStatus isAncCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isAncCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IAncCapability">IAncCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the ANC capability to be used for getting and setting the<br>
   * ANC mode on a device..<br>
   * If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the ANC capability, or nullptr if not supported.
   */
  @Nullable
  public IAncCapability getAncCapability() {
    long cPtr = AspenJNI.IDeviceService_getAncCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IAncCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#IEqualizerCapability">IEqualizerCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_equalizer_capability_supported">is_equalizer_capability_supported</a>.<br>
   * <br>
   * @return True when device service has an equalizer capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsEqualizerCapability() {
    return AspenJNI.IDeviceService_supportsEqualizerCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IEqualizerCapability">IEqualizerCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IEqualizerCapability">IEqualizerCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IEqualizerCapability">IEqualizerCapability</a>.
   */
  public CapabilitySupportStatus isEqualizerCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isEqualizerCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IEqualizerCapability">IEqualizerCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the Equalizer capability used for controlling the equalizer on a device.<br>
   * If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the Equalizer capability, or nullptr if not supported.
   */
  @Nullable
  public IEqualizerCapability getEqualizerCapability() {
    long cPtr = AspenJNI.IDeviceService_getEqualizerCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IEqualizerCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has a <a href="#IDeviceInfoCapability">IDeviceInfoCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_device_info_capability_supported">is_device_info_capability_supported</a>.<br>
   * <br>
   * @return True when device service has a device info capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsDeviceInfoCapability() {
    return AspenJNI.IDeviceService_supportsDeviceInfoCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IDeviceInfoCapability">IDeviceInfoCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IDeviceInfoCapability">IDeviceInfoCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IDeviceInfoCapability">IDeviceInfoCapability</a>.
   */
  public CapabilitySupportStatus isDeviceInfoCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isDeviceInfoCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IDeviceInfoCapability">IDeviceInfoCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the device info capability used for retrieving information regarding<br>
   * the device. If the device service, and thereby its remote audio device does not support this, then<br>
   * a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the device info capability, or nullptr if not supported.
   */
  @Nullable
  public IDeviceInfoCapability getDeviceInfoCapability() {
    long cPtr = AspenJNI.IDeviceService_getDeviceInfoCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IDeviceInfoCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#ISpatializerCapability">ISpatializerCapability</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_spatializer_capability_supported">is_spatializer_capability_supported</a>.<br>
   * <br>
   * @return True when device service has an spatializer capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsSpatializerCapability() {
    return AspenJNI.IDeviceService_supportsSpatializerCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#ISpatializerCapability">ISpatializerCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#ISpatializerCapability">ISpatializerCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#ISpatializerCapability">ISpatializerCapability</a>.
   */
  public CapabilitySupportStatus isSpatializerCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isSpatializerCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#ISpatializerCapability">ISpatializerCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the Spatializer capability used for controlling the spatializer on a<br>
   * device. If the device service, and thereby its remote audio device does not support this,<br>
   * then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the Spatializer capability, or nullptr if not supported
   */
  @Nullable
  public ISpatializerCapability getSpatializerCapability() {
    long cPtr = AspenJNI.IDeviceService_getSpatializerCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new ISpatializerCapability(cPtr, true);
  }

  /**
   * Check whether <a href="#ITuningCapability">ITuningCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#ITuningCapability">ITuningCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#ITuningCapability">ITuningCapability</a>.
   */
  public CapabilitySupportStatus isTuningCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isTuningCapabilitySupported(swigCPtr, this));
  }

  /**
   * Check whether <a href="#IPrototypeCapability">IPrototypeCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IPrototypeCapability">IPrototypeCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IPrototypeCapability">IPrototypeCapability</a>.
   */
  public CapabilitySupportStatus isPrototypeCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isPrototypeCapabilitySupported(swigCPtr, this));
  }

  /**
   * Returns a bool signifying whether the customer is licensed to use the <a href="#IAudiodoTransparency">IAudiodoTransparency</a><br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_audiodo_transparency_capability_supported">is_audiodo_transparency_capability_supported</a>.<br>
   * <br>
   * @return True when customer is licensed to use the prototype capability, false when it not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsAudiodoTransparencyCapability() {
    return AspenJNI.IDeviceService_supportsAudiodoTransparencyCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IAudiodoTransparencyCapability">IAudiodoTransparencyCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IAudiodoTransparencyCapability">IAudiodoTransparencyCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a<br>
   *         <a href="#IAudiodoTransparencyCapability">IAudiodoTransparencyCapability</a>.
   */
  public CapabilitySupportStatus isAudiodoTransparencyCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isAudiodoTransparencyCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IAudiodoTransparency">IAudiodoTransparency</a> for this device service<br>
   * <br>
   * Gets an interface to the audiodo transparency capability.<br>
   * If the device service, and thereby its remote audio device does not<br>
   * support this, then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the capability, or nullptr if not supported.
   */
  @Nullable
  public IAudiodoTransparencyCapability getAudiodoTransparencyCapability() {
    long cPtr = AspenJNI.IDeviceService_getAudiodoTransparencyCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IAudiodoTransparencyCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the device service has an <a href="#IVolumeCapability">IVolumeCapability</a>.<br>
   * <br>
   * @deprecated This function is deprecated in favour of <a href="#is_volume_capability_supported">is_volume_capability_supported</a>.<br>
   * <br>
   * @return True when device service has a volume capability, false when it does not.
   */
  @Nullable
  @Deprecated(since = "1.14.0", forRemoval = true)
  public boolean supportsVolumeCapability() {
    return AspenJNI.IDeviceService_supportsVolumeCapability(swigCPtr, this);
  }

  /**
   * Check whether <a href="#IVolumeCapability">IVolumeCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IVolumeCapability">IVolumeCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IVolumeCapability">IVolumeCapability</a>.
   */
  public CapabilitySupportStatus isVolumeCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isVolumeCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IVolumeCapability">IVolumeCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the volume capability.<br>
   * If the device service, and thereby its remote audio device does not<br>
   * support this, then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the capability, or nullptr if not supported.
   */
  @Nullable
  public IVolumeCapability getVolumeCapability() {
    long cPtr = AspenJNI.IDeviceService_getVolumeCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IVolumeCapability(cPtr, true);
  }

  /**
   * Check whether <a href="#IBassBoostCapability">IBassBoostCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IBassBoostCapability">IBassBoostCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IBassBoostCapability">IBassBoostCapability</a>.
   */
  public CapabilitySupportStatus isBassBoostCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isBassBoostCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IBassBoostCapability">IBassBoostCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the Bass Boost capability used for controlling the bass boost on a<br>
   * device. If the device service, and thereby its remote audio device does not support this,<br>
   * then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the Bass Boost capability, or nullptr if not supported
   */
  @Nullable
  public IBassBoostCapability getBassBoostCapability() {
    long cPtr = AspenJNI.IDeviceService_getBassBoostCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IBassBoostCapability(cPtr, true);
  }

  /**
   * Check whether <a href="#IDetailEnhancerCapability">IDetailEnhancerCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IDetailEnhancerCapability">IDetailEnhancerCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IDetailEnhancerCapability">IDetailEnhancerCapability</a>.
   */
  public CapabilitySupportStatus isDetailEnhancerCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isDetailEnhancerCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IDetailEnhancerCapability">IDetailEnhancerCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the DetailEnhancer capability used for controlling the detail_enhancer on a<br>
   * device. If the device service, and thereby its remote audio device does not support this,<br>
   * then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the DetailEnhancer capability, or nullptr if not supported
   */
  @Nullable
  public IDetailEnhancerCapability getDetailEnhancerCapability() {
    long cPtr = AspenJNI.IDeviceService_getDetailEnhancerCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IDetailEnhancerCapability(cPtr, true);
  }

  /**
   * Check whether <a href="#IAudiosphereIrCapability">IAudiosphereIrCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IAudiosphereIrCapability">IAudiosphereIrCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IAudiosphereIrCapability">IAudiosphereIrCapability</a>.
   */
  public CapabilitySupportStatus isAudiosphereIrCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isAudiosphereIrCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IAudiosphereIrCapability">IAudiosphereIrCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the Audiosphere IR capability used for controlling the effect on a<br>
   * device. If the device service, and thereby its remote audio device does not support this,<br>
   * then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the Audiosphere IR capability, or nullptr if not supported
   */
  @Nullable
  public IAudiosphereIrCapability getAudiosphereIrCapability() {
    long cPtr = AspenJNI.IDeviceService_getAudiosphereIrCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IAudiosphereIrCapability(cPtr, true);
  }

  /**
   * Check whether <a href="#IHeadTrackCapability">IHeadTrackCapability</a> is supported or not<br>
   * <br>
   * Function will always return <a href="#CapabilitySupportStatus::connection_required">CapabilitySupportStatus::connection_required</a> until the callback<br>
   * <a href="#IDeviceServiceCallbacks::session_established">IDeviceServiceCallbacks::session_established</a> has been received. Once it has, the function returns<br>
   * <a href="#CapabilitySupportStatus::supported">CapabilitySupportStatus::supported</a> if the device service has a <a href="#IHeadTrackCapability">IHeadTrackCapability</a>,<br>
   * <a href="#CapabilitySupportStatus::not_supported">CapabilitySupportStatus::not_supported</a> if not.<br>
   * <br>
   * @return CapabilitySupportStatus signifying whether the device service has a <a href="#IHeadTrackCapability">IHeadTrackCapability</a>.
   */
  public CapabilitySupportStatus isHeadtrackCapabilitySupported() {
    return CapabilitySupportStatus.swigToEnum(AspenJNI.IDeviceService_isHeadtrackCapabilitySupported(swigCPtr, this));
  }

  /**
   * Getter for the <a href="#IHeadTrackCapability">IHeadTrackCapability</a> for this device service<br>
   * <br>
   * Gets an interface to the HeadTrack capability used for controlling the effect on a<br>
   * device. If the device service, and thereby its remote audio device does not support this,<br>
   * then a nullptr will be returned.<br>
   * <br>
   * @return A pointer to the HeadTrack capability, or nullptr if not supported
   */
  @Nullable
  public IHeadTrackCapability getHeadtrackCapability() {
    long cPtr = AspenJNI.IDeviceService_getHeadtrackCapability(swigCPtr, this);
    return (cPtr == 0) ? null : new IHeadTrackCapability(cPtr, true);
  }

  /**
   * Returns a bool signifying whether the connection is ok or not<br>
   * <br>
   * Returns a bool signifying whether the connection is ok or not.<br>
   * When earbuds are being used, the connection is considered OK<br>
   * when both earbuds are connected. When only one earbud is connected<br>
   * the return value will be false.<br>
   * <br>
   * @return True when the connection is OK, false when it is not.
   */
  public boolean isConnectionOk() {
    return AspenJNI.IDeviceService_isConnectionOk(swigCPtr, this);
  }

  /**
   * Returns a bool signifying whether the session can be closed by Aspen<br>
   * <br>
   * Function will always return false for devices not supporting that Aspen closes the session<br>
   * <br>
   * @return True when device supports the feature, false otherwise.
   */
  public boolean supportsSessionClose() {
    return AspenJNI.IDeviceService_supportsSessionClose(swigCPtr, this);
  }

  /**
   * Close the current session<br>
   * <br>
   * Function to inform connected device that the client wants to<br>
   * close the current session. This should only be used when the user<br>
   * of this API wants to close a session. It should not be called in case<br>
   * of a transport disconnect. Then on_transport_disconnect() should be called<br>
   * instead.
   */
  public void requestSessionClose() {
    AspenJNI.IDeviceService_requestSessionClose(swigCPtr, this);
  }

}
