/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

import java.util.List;
import androidx.annotation.Nullable;

/**
 *  The Equalizer Profile service<br>
 * <br>
 * Handles saved equalizer profiles. This can be used to store a number of equalizer profiles and<br>
 * then later apply them as the user wish.
 */
public class IEqualizerProfileService {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IEqualizerProfileService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEqualizerProfileService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IEqualizerProfileService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Create a new equalizer profile object with the provided information<br>
   * <br>
   * This is a synchronous request which may take some time due to saving to disk.<br>
   * <br>
   * Creates a new EqualizerProfile object and stores it in persistent storage.<br>
   * <br>
   * @param name The name of the equalizer profile<br>
   * @param eq_config The frequency and gain values that should be stored with this equalizer profile<br>
   * <br>
   * @return Returns the newly created EqualizerProfile object
   */
  public EqualizerProfile createProfile(String name, EqualizerConfiguration eq_config, EqualizerPositions positions) {
    return new EqualizerProfile(AspenJNI.IEqualizerProfileService_createProfile(swigCPtr, this, name, EqualizerConfiguration.getCPtr(eq_config), eq_config, EqualizerPositions.getCPtr(positions), positions), true);
  }

  /**
   * Get a copy of all the stored profiles<br>
   * <br>
   * A synchronous request to fetch a copy of a vector containing the profiles.<br>
   * <br>
   * @return A copy of a vector with all of the stored profiles
   */
  public List<EqualizerProfile> getProfiles() {
    return AspenJNI.IEqualizerProfileService_getProfiles(swigCPtr, this);
}

  /**
   * Get a copy of the stored profile by id<br>
   * <br>
   * A synchronous operation to fetch a copy of a profile with a matching id. If no profile<br>
   * with a matching ID is found, null is returned.<br>
   * <br>
   * @param id The id of the profile to fetch<br>
   * <br>
   * @return A copy of an EqualizerProfile object containing the profile's data, or NULL if no profile with<br>
   *         matching id is found
   */
  @Nullable
  public EqualizerProfile getProfile(String id) {
    long cPtr = AspenJNI.IEqualizerProfileService_getProfile(swigCPtr, this, id);
    return (cPtr == 0) ? null : new EqualizerProfile(cPtr, true);
}

  /**
   * Save an EqualizerProfile<br>
   * <br>
   * This is a synchronous operation which may take some time due to saving to disk.<br>
   * <br>
   * If the id of the EqualizerProfile matches the id of an existing EqualizerProfile, the EqualizerProfile<br>
   * will be updated. If not, a new EqualizerProfile will be created and saved.<br>
   * <br>
   * @param profile The EqualizerProfile to save
   */
  public void saveProfile(EqualizerProfile profile) {
    AspenJNI.IEqualizerProfileService_saveProfile(swigCPtr, this, EqualizerProfile.getCPtr(profile), profile);
  }

  /**
   * Remove a profile<br>
   * <br>
   * This is a synchronous operation which may take some time due to saving to disk. If no profile<br>
   * with a matching ID is found, no profile is removed and false is returned.<br>
   * <br>
   * @param id The id of the profile to remove<br>
   * <br>
   * @return Returns true if profile was successfully removed, false if not
   */
  public boolean removeProfile(String id) {
    return AspenJNI.IEqualizerProfileService_removeProfile(swigCPtr, this, id);
  }

}
