/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The equalizer capability<br>
 * <br>
 * This class is an interface to the equalizer capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to perform actions on the equalizer.<br>
 * <br>
 * On session established the capability will start a synchronize process with the remove<br>
 * device. During this time most of the API calls will be blocked. When sync is complete the<br>
 * observer event <a href="#get_observable_event_sync_complete">get_observable_event_sync_complete</a> will be sent.
 */
public class IEqualizerCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IEqualizerCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IEqualizerCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEqualizerCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IEqualizerCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Activate the equalizer.<br>
   * <br>
   * An asynchronous request to activate the equalizer. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_confirmation">get_observable_event_activate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.<br>
   * <br>
   * Note: The equalizer can be controlled independently of the profile but a profile has<br>
   * to be active for the equalizer to have any affect, see <a href="#is_bypassed">is_bypassed</a>.
   */
  public void activate() {
    AspenJNI.IEqualizerCapability_activate(swigCPtr, this);
  }

  /**
   * Deactivate the equalizer.<br>
   * <br>
   * An asynchronous request to deactivate the equalizer. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_confirmation">get_observable_event_deactivate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivate() {
    AspenJNI.IEqualizerCapability_deactivate(swigCPtr, this);
  }

  /**
   * Set a configuration on the equalizer.<br>
   * <br>
   * An asynchronous request to set a new equalizer configuration (not persistent, @see save). Observers will be notified with event when the change has been confirmed by the remote device.<br>
   * <br>
   * It is allowed to call this function before a confirmation has been received on the<br>
   * previous request. In this case it's not guaranteed that each call will receive a<br>
   * confirmation event. When a confirmation is received, the latest known config will be<br>
   * sent, any possible earlier requests will never be sent.<br>
   * <br>
   * The equalizer does not need to be activated to set gains.<br>
   * <br>
   * Note: To make the changes persistent a call to <a href="#save">save</a> is required.<br>
   * <br>
   * @param configuration Configuration to set.
   */
  public void set(EqualizerConfiguration configuration) {
    AspenJNI.IEqualizerCapability_set(swigCPtr, this, EqualizerConfiguration.getCPtr(configuration), configuration);
  }

  /**
   * Reset the configuration of the equalizer.<br>
   * <br>
   * This method resets the equalizer configuration to default.<br>
   * The effect is the same as calling <a href="#set">set</a> with all gains set to zero.
   */
  public void reset() {
    AspenJNI.IEqualizerCapability_reset(swigCPtr, this);
  }

  /**
   * Check if the equalizer is activated.<br>
   * <br>
   * @return True if it is activated, false if it is deactivated.
   */
  public boolean isActivated() {
    return AspenJNI.IEqualizerCapability_isActivated(swigCPtr, this);
  }

  /**
   * Check if the capability is in sync with the audio device.<br>
   * <br>
   * @return True if it is in sync, false if not in sync.
   */
  public boolean remoteDeviceInSync() {
    return AspenJNI.IEqualizerCapability_remoteDeviceInSync(swigCPtr, this);
  }

  /**
   * Persistent save of the configuration<br>
   * <br>
   * Saves the equalizer configuration on the audio device together<br>
   * with the currently set id on the audio device.<br>
   * <br>
   * This should be used after <a href="#set">set</a> to make the changes persistent.
   */
  public void save() {
    AspenJNI.IEqualizerCapability_save__SWIG_0(swigCPtr, this);
  }

  /**
   * Persistent save of the configuration for the id<br>
   * <br>
   * An asynchronous request to save the configuration and the<br>
   * passed in id persistently on the audio device. The id should be<br>
   * fetched from an <a href="#EqualizerProfile">EqualizerProfile</a>. The request will be sent<br>
   * to the audio device if the id or the equalizer configuration differs.<br>
   * <br>
   * Observers will be notified with the event <a href="#get_observable_event_save_confirmation">get_observable_event_save_confirmation</a><br>
   * when the change has been confirmed by the audio device.<br>
   * <br>
   * This should be used after <a href="#set">set</a> to make the changes persistent.<br>
   * <br>
   * @param id The id of the equalizer configuration
   */
  public void save(String id) {
    AspenJNI.IEqualizerCapability_save__SWIG_1(swigCPtr, this, id);
  }

  /**
   * Get the configuration object<br>
   * <br>
   * @return The EqualizerConfiguration object
   */
  public EqualizerConfiguration getConfiguration() {
    return new EqualizerConfiguration(AspenJNI.IEqualizerCapability_getConfiguration(swigCPtr, this), true);
  }

  /**
   * Get the id set on the equalizer on the audio device<br>
   * <br>
   * A synchronous request to get the id. Returns the id on the audio device when it is in<br>
   * sync, @see remote_device_in_sync. If not, it will return the last known id.<br>
   * <br>
   * @return The id as a string
   */
  public String getId() {
    return AspenJNI.IEqualizerCapability_getId(swigCPtr, this);
  }

  /**
   * Check if the equalizer is bypassed<br>
   * <br>
   * Check if the Equalizer processing is bypassed. A bypassed equalizer will not be<br>
   * processing audio even if its activated. The Equalizer is bypassed if the Audiodo<br>
   * personal sound processing is disabled. The API is still open for use and any changes<br>
   * will be saved.<br>
   * <br>
   * @return True if the equalizer is bypassed, false if not bypassed.
   */
  public boolean isBypassed() {
    return AspenJNI.IEqualizerCapability_isBypassed(swigCPtr, this);
  }

  /**
   *  Notification that the capability is in sync with device<br>
   * <br>
   * On session establish the equalizer capability will synchronize with the remote<br>
   * device. On completion the observers will be notified with this event. The subject<br>
   * parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSyncComplete() {
    return AspenJNI.IEqualizerCapability_getObservableEventSyncComplete();
  }

  /**
   *  Confirmation from device that the equalizer is activated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate">activate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateConfirmation() {
    return AspenJNI.IEqualizerCapability_getObservableEventActivateConfirmation();
  }

  /**
   *  Confirmation from device that the equalizer is deactivated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate">deactivate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateConfirmation() {
    return AspenJNI.IEqualizerCapability_getObservableEventDeactivateConfirmation();
  }

  /**
   *  Confirmation from device that the equalizer was saved<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#save">save</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSaveConfirmation() {
    return AspenJNI.IEqualizerCapability_getObservableEventSaveConfirmation();
  }

  /**
   *  Confirmation from device that the equalizer configuration was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set">set</a> or <a href="#reset">reset</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * Note: If multiple set or reset requests are done before a confirmation all requests<br>
   * might not receive a confirmation. Only the latest known value will be sent and<br>
   * confirmed in this case.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetConfirmation() {
    return AspenJNI.IEqualizerCapability_getObservableEventSetConfirmation();
  }

  /**
   * Observer event notifying that the Equalizer was bypassed<br>
   * <br>
   * Observer will be notified with this event when the Equalizer has been bypassed.<br>
   * See <a href="#is_bypassed">is_bypassed</a> for more information.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventBypassed() {
    return AspenJNI.IEqualizerCapability_getObservableEventBypassed();
  }

  /**
   * Observer event notifying that the Equalizer's bypass was removed<br>
   * <br>
   * Observer will be notified with this event when the Equalizer's bypass has been removed.<br>
   * See <a href="#is_bypassed">is_bypassed</a> for more information.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventBypassRemoved() {
    return AspenJNI.IEqualizerCapability_getObservableEventBypassRemoved();
  }

}
