/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class IHeadTrackCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IHeadTrackCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IHeadTrackCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IHeadTrackCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IHeadTrackCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Set the HeadTrackState<br>
   * <br>
   * An asynchronous request to set the state of the HeadTrackCapability. Observers will be notified with<br>
   * event <a href="#get_observable_event_set_state_confirmation">get_observable_event_set_state_confirmation</a> when the change has been<br>
   * confirmed by the remote device.<br>
   * <br>
   * @param state The desired state
   */
  public void setState(HeadTrackState state) {
    AspenJNI.IHeadTrackCapability_setState(swigCPtr, this, state.swigValue());
  }

  /**
   * Returns the current state<br>
   * <br>
   * @return The current state
   */
  public HeadTrackState getState() {
    return HeadTrackState.swigToEnum(AspenJNI.IHeadTrackCapability_getState(swigCPtr, this));
  }

  /**
   * Resets the head tracking orientation<br>
   * <br>
   * An asynchronous request to reset the head tracking orientation. Observers will be notified with<br>
   * event <a href="#get_observable_event_reset_confirmation">get_observable_event_reset_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void reset() {
    AspenJNI.IHeadTrackCapability_reset(swigCPtr, this);
  }

  /**
   * Activates the auto-reset feature for head tracking<br>
   * <br>
   * NOTE: Only supported if <a href="#is_auto_reset_supported">is_auto_reset_supported</a> returns true.<br>
   * <br>
   * Auto-reset automatically resets the head tracking orientation when the user<br>
   * has remained still for a defined period of time.<br>
   * <br>
   * An asynchronous request to activate auto reset for head tracking. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_auto_reset_confirmation">get_observable_event_activate_auto_reset_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void activateAutoReset() {
    AspenJNI.IHeadTrackCapability_activateAutoReset(swigCPtr, this);
  }

  /**
   * Deactivates the auto-reset feature for head tracking<br>
   * <br>
   * NOTE: Only supported if <a href="#is_auto_reset_supported">is_auto_reset_supported</a> returns true.<br>
   * <br>
   * See <a href="#activate_auto_reset">activate_auto_reset</a> for more info.<br>
   * <br>
   * An asynchronous request to deactivate auto reset for head tracking. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_auto_reset_confirmation">get_observable_event_deactivate_auto_reset_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivateAutoReset() {
    AspenJNI.IHeadTrackCapability_deactivateAutoReset(swigCPtr, this);
  }

  /**
   * Check if auto-reset is active<br>
   * <br>
   * NOTE: Only supported if <a href="#is_auto_reset_supported">is_auto_reset_supported</a> returns true.<br>
   * <br>
   * If interaction with the auto-reset feature is not supported, this function<br>
   * will return false. The feature may still be active on the device, but its<br>
   * state cannot be modified.<br>
   * <br>
   * @return True if it is active, false if inactive.
   */
  public boolean isAutoResetActive() {
    return AspenJNI.IHeadTrackCapability_isAutoResetActive(swigCPtr, this);
  }

  /**
   * Check if the auto-reset feature is supported<br>
   * <br>
   * Determines if the auto-reset feature can be interacted with on the device. The feature<br>
   * may be supported by the device, but still not allow certain operations, such as requesting<br>
   * deactivation.<br>
   * <br>
   * @return True if it is supported, false if not.
   */
  public boolean isAutoResetSupported() {
    return AspenJNI.IHeadTrackCapability_isAutoResetSupported(swigCPtr, this);
  }

  /**
   *  Confirmation from device that the state has been set.<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_state">set_state</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetStateConfirmation() {
    return AspenJNI.IHeadTrackCapability_getObservableEventSetStateConfirmation();
  }

  /**
   *  Confirmation from device that the head tracking orientation has been reset.<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#reset">reset</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventResetConfirmation() {
    return AspenJNI.IHeadTrackCapability_getObservableEventResetConfirmation();
  }

  /**
   *  Confirmation from device that the auto-reset feature has been activated.<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate_auto_reset">activate_auto_reset</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateAutoResetConfirmation() {
    return AspenJNI.IHeadTrackCapability_getObservableEventActivateAutoResetConfirmation();
  }

  /**
   *  Confirmation from device that the auto-reset feature has been deactivated.<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate_auto_reset">deactivate_auto_reset</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateAutoResetConfirmation() {
    return AspenJNI.IHeadTrackCapability_getObservableEventDeactivateAutoResetConfirmation();
  }

}
