/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

import java.util.concurrent.CopyOnWriteArrayList;
import java.util.List;

/**
 *  The observable interface<br>
 * <br>
 * The interface that any observable class must implement.
 */
public class IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IObservableProperty(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IObservableProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IObservableProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
  private List<IPropertyObserver> observers = new CopyOnWriteArrayList<>();
  /**
   *  A method to add an observer<br>
   * <br>
   * @param observer The IPropertyObserver observer to add.
   */
  public void addObserver(IPropertyObserver observer) {
    AspenJNI.IObservableProperty_addObserver(swigCPtr, this, IPropertyObserver.getCPtr(observer), observer);
    observers.add(observer);
  }

  /**
   *  A method to remove an observer<br>
   * <br>
   * @param observer The IPropertyObserver observer to remove.
   */
  public void removeObserver(IPropertyObserver observer) {
    AspenJNI.IObservableProperty_removeObserver(swigCPtr, this, IPropertyObserver.getCPtr(observer), observer);
    observers.remove(observer);
  }

}
