/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;
import androidx.annotation.Nullable;
/**
 *  The profile capability<br>
 * <br>
 * This class is an interface to the profile capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to control which profile is uploaded to the device as well as activating<br>
 * and deactivating personal sound.<br>
 * <br>
 * The caller should implement a subclass of <a href="#IPropertyObserver">IPropertyObserver</a> to get the asynchronous<br>
 * result of some of the method calls in this class.
 */
public class IProfileCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IProfileCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IProfileCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IProfileCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IProfileCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Activate a profile on the device<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is get_observable_event_activated, and the subject<br>
   * passed is the profile's ID string.<br>
   * <br>
   * Initial errors are communicated through the boolean return value, asynchronous errors<br>
   * will result in the device session being terminated, and the user will have to determine<br>
   * proper cause of action.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * This method activates the profile on the connected remote device. If not present on<br>
   * the device already it is uploaded as well.<br>
   * <br>
   * @deprecated This function is deprecated in favour <a href="#set_remote_profile">set_remote_profile</a> and<br>
   * <a href="#activate_personal_sound">activate_personal_sound</a>. This will be removed in a upcoming release.<br>
   * <br>
   * @param profile_id The id of the profile to activate<br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  @Deprecated(since = "0.7.3", forRemoval = true)
  public boolean activate(String profile_id) {
    return AspenJNI.IProfileCapability_activate(swigCPtr, this, profile_id);
  }

  /**
   *  Activates personal sound using the current remote profile<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is <a href="#get_observable_event_activated">get_observable_event_activated</a><br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  public boolean activatePersonalSound() {
    return AspenJNI.IProfileCapability_activatePersonalSound(swigCPtr, this);
  }

  /**
   *  Set the remote profile<br>
   * <br>
   * This method sets the profile on the connected remote device. If there is any existing<br>
   * profile on the device it will be overwritten. The personal sound processing will keep the<br>
   * previous state, i.e if the processing was enabled on the previous profile the new profile<br>
   * will also ahve it activated. If there was no previous profile it will not be activated. Use<br>
   * <a href="#activate_personal_sound">activate_personal_sound</a>.<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is <a href="#get_observable_event_profile_set">get_observable_event_profile_set</a><br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * @param profile_id The id of the profile to activate<br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  public boolean setRemoteProfile(String profile_id) {
    return AspenJNI.IProfileCapability_setRemoteProfile(swigCPtr, this, profile_id);
  }

  /**
   *  Deactivate a profile on the device<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is get_observable_event_activated, and the subject<br>
   * passed is the profile's ID string.<br>
   * <br>
   * Initial errors are communicated through the boolean return value, asynchronous errors<br>
   * will result in the device session being terminated, and the user will have to determine<br>
   * proper cause of action.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * @deprecated Renamed to deactivate_personal_sound to make it more consistent with<br>
   * the activate counterpart.<br>
   * <br>
   * This method deactivates the current profile on the connected remote device.<br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  public boolean deactivate() {
    return AspenJNI.IProfileCapability_deactivate(swigCPtr, this);
  }

  /**
   *  Deactivate personal sound on the device<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is get_observable_event_activated, and the subject<br>
   * passed is the profile's ID string.<br>
   * <br>
   * Initial errors are communicated through the boolean return value, asynchronous errors<br>
   * will result in the device session being terminated, and the user will have to determine<br>
   * proper cause of action.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * This method deactivates the current profile on the connected remote device.<br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  public boolean deactivatePersonalSound() {
    return AspenJNI.IProfileCapability_deactivatePersonalSound(swigCPtr, this);
  }

  /**
   *  Clear a profile on the device<br>
   * <br>
   * A successful operation will result in an event in the observer's propertyChanged()<br>
   * method. The event that matches this call is observableEventActivated, and the subject<br>
   * passed is the profile's ID string.<br>
   * <br>
   * Initial errors are communicated through the boolean return value, asynchronous errors<br>
   * will result in the device session being terminated, and the user will have to determine<br>
   * proper cause of action.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * If this method is called while there is an ongoing request through the ProfileCapability,<br>
   * it will return false until that request is processed. Use the events to know when a<br>
   * request is done.<br>
   * <br>
   * This method clears the current profile on the connected remote device.<br>
   * @return True if the initial handling went well, false if something immediately went wrong
   */
  public boolean clear() {
    return AspenJNI.IProfileCapability_clear(swigCPtr, this);
  }

  /**
   *  Get the profile retrieved from the remote device<br>
   * <br>
   * If a headset has a profile loaded when Aspen connects to it, ProfileCapability<br>
   * will download it, and this method lets the Aspen user access that profile.<br>
   * It is not valid (and the return value will be NULL) until any existing profile<br>
   * has been downloaded.<br>
   * <br>
   * When ProfileCapability has connected and downloaded the profile, if one exists,<br>
   * one of four events will be posted to the PropertyObserver, signalling that this<br>
   * data is available.<br>
   * - If get_observable_event_no_remote_profile() is posted, no profile is available.<br>
   * - If get_observable_event_new_remote_profile() is posted, a new profile is available.<br>
   * - If get_observable_event_existing_remote_profile() is posted, a profile is available<br>
   * that is already present in the ProfileSet.<br>
   * - If get_observable_event_differing_existing_remote_profile() is posted, a profile<br>
   * is available is already present in the ProfileSet, but with a different name.<br>
   * <br>
   * @return A ProfileData object containing the Profile's data, or NULL if there<br>
   *         is none or if it has not been downloaded yet.
   */
  @Nullable
  public ProfileData getRemoteProfile() {
    long cPtr = AspenJNI.IProfileCapability_getRemoteProfile(swigCPtr, this);
    return (cPtr == 0) ? null : new ProfileData(cPtr, true);
}

  /**
   *  Get the sound processing status, on/off<br>
   * <br>
   * This method allows the Aspen user to check whether a connected headset has<br>
   * its sound processing on or off.<br>
   * It is not valid (and it will report "off") until any existing profile has been<br>
   * downloaded.<br>
   * <br>
   * When ProfileCapability has connected and downloaded the profile, if one exists,<br>
   * one of four events will be posted to the PropertyObserver, signalling that this<br>
   * method will be reliable.<br>
   * - get_observable_event_no_remote_profile()<br>
   * - get_observable_event_new_remote_profile()<br>
   * - get_observable_event_existing_remote_profile()<br>
   * - get_observable_event_differing_existing_remote_profile()<br>
   * <br>
   * @return True if processing is on in the headset, false if it is off.
   */
  public boolean processingOn() {
    return AspenJNI.IProfileCapability_processingOn(swigCPtr, this);
  }

  /**
   *  Check if remote device status is up to date<br>
   * <br>
   * This method allows the Aspen user to check if the remote device status is in sync,<br>
   * i.e. whether the information about the remote device is up to date, like<br>
   * processing_on() and get_remote_profile(). When disconnected, those APIs will<br>
   * return the status from when the device was last connected.<br>
   * There are observer events for when processing and remote profile status changes,<br>
   * but this method can be useful for getting an immediate update.<br>
   * <br>
   * When not in sync, that means that the current information might or might not<br>
   * properly reflect the status in the device – we just don't know, and the status<br>
   * we have is what we last knew to be true.<br>
   * <br>
   * @return True if the remote device status is in sync, false if not in sync.
   */
  public boolean remoteDeviceInSync() {
    return AspenJNI.IProfileCapability_remoteDeviceInSync(swigCPtr, this);
  }

  /**
   *  Accept the profile retrieved from device<br>
   * <br>
   * The method can be used after a new or differing profile has been fetched from the<br>
   * device. Accepting a profile will keep it on the device and update the profile set<br>
   * accordingly.<br>
   * <br>
   * - If it's a new profile it will be added to the profile set<br>
   * - If it's an existing profile nothing will be done to the profile set<br>
   * - If it's an existing differing profile, the existing profile will be updated
   */
  public void acceptProfile() {
    AspenJNI.IProfileCapability_acceptProfile(swigCPtr, this);
  }

  /**
   *  Reject the profile retrieved from device<br>
   * <br>
   * This method can be used after a new or differing profile has been fetched from<br>
   * the device. Rejecting a profile will clear it on the device but will not affect<br>
   * the profile set in any way.
   */
  public void rejectProfile() {
    AspenJNI.IProfileCapability_rejectProfile(swigCPtr, this);
  }

  /**
   *  Get the minimum compensation offset<br>
   * <br>
   * NOTE: This API is only supported for personal sound V3.<br>
   * <br>
   * A connected audio device is required. If no audio device is connected, the function<br>
   * will return 0.<br>
   * <br>
   * @return The minimum compensation offset
   */
  public byte getMinCompensationOffset() {
    return AspenJNI.IProfileCapability_getMinCompensationOffset(swigCPtr, this);
  }

  /**
   *  Get the maximum compensation offset<br>
   * <br>
   * NOTE: This API is only supported for personal sound V3.<br>
   * <br>
   * A connected audio device is required. If no audio device is connected, the function<br>
   * will return 0.<br>
   * <br>
   * @return The maximum compensation offset
   */
  public byte getMaxCompensationOffset() {
    return AspenJNI.IProfileCapability_getMaxCompensationOffset(swigCPtr, this);
  }

  /**
   *  Set compensation offset<br>
   * <br>
   * NOTE: This API is only supported for personal sound V3.<br>
   * <br>
   * NOTE: If called when the corresponding Aspen state already is as expected, the method<br>
   * will return true and also send the matching event; the rationale is that if the caller<br>
   * wants to do this action, there might be follow-up logic that the caller expects to be<br>
   * done in the event handler that wouldn't be executed if we just silently returned.<br>
   * <br>
   * A successful operation will result in an event in the observer's property_changed()<br>
   * method. The event that matches this call is get_observable_event_comp_offset_changed.<br>
   * <br>
   * @param value The degree of compensation
   */
  public void setCompensationOffset(byte value) {
    AspenJNI.IProfileCapability_setCompensationOffset(swigCPtr, this, value);
  }

  /**
   *  Get compensation offset<br>
   * <br>
   * NOTE: This API is only supported for personal sound V3.<br>
   * <br>
   * @return Returns the currently set value for the compensation offset.
   */
  public byte getCompensationOffset() {
    return AspenJNI.IProfileCapability_getCompensationOffset(swigCPtr, this);
  }

  /**
   *  Getter for personal sound version<br>
   * <br>
   * If there is no connection to an audio device, the function will return version UNKNOWN.<br>
   * <br>
   * @return Returns the personal sound version
   */
  public PersonalSoundVersion getPsVersion() {
    return PersonalSoundVersion.swigToEnum(AspenJNI.IProfileCapability_getPsVersion(swigCPtr, this));
  }

  /**
   *  The event for connecting to a remote device that has no profile<br>
   * <br>
   * When ProfileCapability has connected to a headset that has no profile loaded,<br>
   * an event is sent to the IPropertyObserver property_changed().<br>
   * <br>
   * This method can be used to get the string constant that identifies that event.<br>
   * When receiving this event (or any other remote profile event), the ProfileCapability<br>
   * is completely ready to use, in sync with the headset.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventNoRemoteProfile() {
    return AspenJNI.IProfileCapability_getObservableEventNoRemoteProfile();
  }

  /**
   *  The event for receiving a new remote profile<br>
   * <br>
   * When ProfileCapability has fetched a profile from the headset that is not already<br>
   * in the ProfileSet, an event is sent to the IPropertyObserver property_changed().<br>
   * The accept_profile or reject_profile functions should be used after this event in<br>
   * order to decide what to do with the remote profile.<br>
   * <br>
   * This method can be used to get the string constant that identifies that event.<br>
   * When receiving this event (or any other remote profile event), the ProfileCapability<br>
   * is completely ready to use, in sync with the headset.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventNewRemoteProfile() {
    return AspenJNI.IProfileCapability_getObservableEventNewRemoteProfile();
  }

  /**
   *  The event for receiving an existing remote profile<br>
   * <br>
   * When ProfileCapability has fetched a profile from the headset that already exists<br>
   * in the ProfileSet, an event is sent to the IPropertyObserver property_changed().<br>
   * <br>
   * This method can be used to get the string constant that identifies that event.<br>
   * When receiving this event (or any other remote profile event), the ProfileCapability<br>
   * is completely ready to use, in sync with the headset.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventExistingRemoteProfile() {
    return AspenJNI.IProfileCapability_getObservableEventExistingRemoteProfile();
  }

  /**
   *  The event for receiving an existing remote profile with a different name<br>
   * <br>
   * When ProfileCapability has fetched a profile from the headset that is already<br>
   * in the ProfileSet but with different name, an event is sent to the IPropertyObserver<br>
   * property_changed(). The accept_profile or reject_profile functions should be used<br>
   * after this event in order to decide what to do with the remote profile.<br>
   * <br>
   * This method can be used to get the string constant that identifies that event.<br>
   * When receiving this event (or any other remote profile event), the ProfileCapability<br>
   * is completely ready to use, in sync with the headset.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDifferingExistingRemoteProfile() {
    return AspenJNI.IProfileCapability_getObservableEventDifferingExistingRemoteProfile();
  }

  /**
   *  The profile activated event<br>
   * <br>
   * This method can be used to get the string constant that identifies when a profile<br>
   * has been activated.<br>
   * To be used in the Observable's property changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivated() {
    return AspenJNI.IProfileCapability_getObservableEventActivated();
  }

  /**
   *  The remote profile set event<br>
   * <br>
   * This event is a confirmation of a <a href="#set_remote_profile">set_remote_profile</a> request. The subject parameter will be set<br>
   * to the ID of the profile.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventProfileSet() {
    return AspenJNI.IProfileCapability_getObservableEventProfileSet();
  }

  /**
   *  The personal sound deactivated event<br>
   * <br>
   * This method can be used to get the string constant that identifies when personal sound<br>
   * has been deactivated.<br>
   * To be used in the Observable's property changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivated() {
    return AspenJNI.IProfileCapability_getObservableEventDeactivated();
  }

  /**
   *  The profile cleared event<br>
   * <br>
   * This method can be used to get the string constant that identifies when a profile<br>
   * has been cleared.<br>
   * To be used in the Observable's property changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventCleared() {
    return AspenJNI.IProfileCapability_getObservableEventCleared();
  }

  /**
   *  The compensation offset changed event<br>
   * <br>
   * This method can be used to get the string constant that identifies when the compensation offset has<br>
   * changed.<br>
   * To be used in the Observable's property changed method.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventCompOffsetChanged() {
    return AspenJNI.IProfileCapability_getObservableEventCompOffsetChanged();
  }

}
