/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;
import androidx.annotation.Nullable;
/**
 *  The Profile service<br>
 * <br>
 * This class is the profile service, providing access to the profile<br>
 * functionality in Aspen.<br>
 * <br>
 * The ProfileService class implements Aspen's observable pattern, so it is possible<br>
 * for a user to subclass <a href="#IPropertyObserver">IPropertyObserver</a> to get updates about changes.
 */
public class IProfileService extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IProfileService(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IProfileService_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IProfileService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IProfileService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the observable event for profile name changes<br>
   * <br>
   * This event is used to notify observers of any name changes to a<br>
   * profile. The subject is the ID of the profile that changed.<br>
   * <br>
   * @return Returns an std::string with the event name.
   */
  public static String getObservableEventProfileName() {
    return AspenJNI.IProfileService_getObservableEventProfileName();
  }

  /**
   * Get the observable event for new profiles<br>
   * <br>
   * This event is used to notify observers whenever a new profile is<br>
   * saved. The subject is the ID of the profile that changed.<br>
   * <br>
   * @return Returns an std::string with the event name.
   */
  public static String getObservableEventProfileAdded() {
    return AspenJNI.IProfileService_getObservableEventProfileAdded();
  }

  /**
   * Get the observable event for removal of profiles<br>
   * <br>
   * This event is used to notify observers whenever a profile is removed.<br>
   * The subject is the ID of the profile that got deleted.<br>
   * <br>
   * @return Returns an std::string with the event name.
   */
  public static String getObservableEventProfileRemoved() {
    return AspenJNI.IProfileService_getObservableEventProfileRemoved();
  }

  /**
   *  Remove profile from profile set<br>
   * <br>
   * This method removes a profile from the profile set in the profile service,<br>
   * and handles all administration concerning the removal.<br>
   * <br>
   * @param profile The profile object to remove
   */
  public void removeProfile(ProfileData profile) {
    AspenJNI.IProfileService_removeProfile(swigCPtr, this, ProfileData.getCPtr(profile), profile);
  }

  /**
   *  Save profile to profile set<br>
   * <br>
   * This method saves a profile to the profile set in the profile service, and<br>
   * handles all administration concerning the saving.<br>
   * <br>
   * @param name The name of the profile.<br>
   * @param age The person's age.<br>
   * @param gender The person's gender.<br>
   * @param result The person's calibration result.
   */
  public void saveProfile(String name, long age, Gender gender, ICalibrationResult result) {
    AspenJNI.IProfileService_saveProfile(swigCPtr, this, name, age, gender.swigValue(), ICalibrationResult.getCPtr(result), result);
  }

  /**
   *  Get a list of all profiles<br>
   * <br>
   * This method returns a list of all available profiles. The list is<br>
   * built on request, any changes to the list will not propagate to the<br>
   * profile set in this service.<br>
   * <br>
   * @return A list of ProfileData objects
   */
  public ProfileDataList getProfiles() {
    return new ProfileDataList(AspenJNI.IProfileService_getProfiles(swigCPtr, this), true);
  }

  /**
   *  Get a copy of a profile's data from its id<br>
   * <br>
   * This method retrieves a copy of a profile's data from the set.<br>
   * <br>
   * @param id The id of the profile to get<br>
   * @return A ProfileData object if the profile exists
   */
  @Nullable
  public ProfileData getProfile(String id) {
    long cPtr = AspenJNI.IProfileService_getProfile(swigCPtr, this, id);
    return (cPtr == 0) ? null : new ProfileData(cPtr, true);
}

  /**
   *  Get number of available profiles<br>
   * <br>
   * This method returns the number of available profiles in the set.<br>
   * <br>
   * @return The number of available profiles
   */
  public long numberOfProfiles() {
    return AspenJNI.IProfileService_numberOfProfiles(swigCPtr, this);
  }

  /**
   *  Set the name of a profile<br>
   * <br>
   * Update the name of an existing profile. The call will be ignored if<br>
   * the profile is unknown to the service.<br>
   * <br>
   * @param profile The profile object to update<br>
   * @param name The name to set<br>
   * @return The updated profile or nullopt if it failed
   */
  public ProfileData setProfileName(ProfileData profile, String name) {
    long cPtr = AspenJNI.IProfileService_setProfileName(swigCPtr, this, ProfileData.getCPtr(profile), profile, name);
    return (cPtr == 0) ? null : new ProfileData(cPtr, true);
}

  /**
   *  Export a hearing profile<br>
   * <br>
   * Exports a hearing profile that can be imported in another Aspen instance.<br>
   * <br>
   * @param profile_id The id of the profile to export<br>
   * @return An encrypted and base64 encoded representation of the profile. Empty string if not found.
   */
  public String exportProfile(String profile_id) {
    return AspenJNI.IProfileService_exportProfile(swigCPtr, this, profile_id);
  }

  /**
   *  Import a profile into the profile set<br>
   * <br>
   * Imports a profile that has been exported previously. Can only be<br>
   * imported from an export. The import does integrity checks on the<br>
   * provided data and will fail if profile data is not acceptable.<br>
   * A profile can not be imported if it already exists in the set.<br>
   * <br>
   * @param profile_blob The profile as previously exported<br>
   * @return true If profile was successfully imported<br>
   * @return false If profile could not be imported
   */
  public boolean importProfile(String profile_blob) {
    return AspenJNI.IProfileService_importProfile(swigCPtr, this, profile_blob);
  }

}
