/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The Property observer class<br>
 * <br>
 * This class represents an observer of an observable property, i.e. a class that<br>
 * wants to observe a property in a class implementing Aspen's generic observable<br>
 * pattern API should subclass this.<br>
 * <br>
 * Note: A subclass of this must overload property_changed
 */
public class IPropertyObserver {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPropertyObserver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPropertyObserver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPropertyObserver obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IPropertyObserver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AspenJNI.IPropertyObserver_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AspenJNI.IPropertyObserver_change_ownership(this, swigCPtr, true);
  }

  /**
   * The observer's notification callback.<br>
   * <br>
   * This method is called whenever an observed object has changed.<br>
   * A class that inherits from this class must implement this method.<br>
   * The two strings passed into the method are defined completely by the<br>
   * observable class in question, so for an exact description of what to<br>
   * expect, see the documentation for those classes.<br>
   * <br>
   * A common usage could be that the event string contains information<br>
   * about what has happened, and the subject can contain e.g. a reference<br>
   * to the affected object, or an additional message of some sort.<br>
   * <br>
   * @param event A string, defined by the concrete implementation of the notification<br>
   *              sender, that states what the update is related to (e.g. a profile's<br>
   *              name change).<br>
   * @param subject A string defining the object related to the update (typically UUID).
   */
  public void propertyChanged(String event, String subject) {
    AspenJNI.IPropertyObserver_propertyChanged(swigCPtr, this, event, subject);
  }

  public IPropertyObserver() {
    this(AspenJNI.new_IPropertyObserver(), true);
    AspenJNI.IPropertyObserver_director_connect(this, swigCPtr, true, true);
  }

}
