/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The Spatializer capability<br>
 * <br>
 * This class is an interface to the spatializer capability available on a <a href="#IDeviceService">IDeviceService</a>.<br>
 * It can be used to perform actions on the spatializer.<br>
 * <br>
 * On session established the capability will start a synchronize process with the remote<br>
 * device. During this time most of the API calls will be blocked. When sync is complete the<br>
 * observer event <a href="#get_observable_event_sync_complete">get_observable_event_sync_complete</a> will be sent.
 */
public class ISpatializerCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ISpatializerCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.ISpatializerCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ISpatializerCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_ISpatializerCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Activate the spatializer.<br>
   * <br>
   * An asynchronous request to activate the spatializer. Observers will be notified with<br>
   * event <a href="#get_observable_event_activate_confirmation">get_observable_event_activate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void activate() {
    AspenJNI.ISpatializerCapability_activate(swigCPtr, this);
  }

  /**
   * Deactivate the spatializer.<br>
   * <br>
   * An asynchronous request to deactivate the spatializer. Observers will be notified with<br>
   * event <a href="#get_observable_event_deactivate_confirmation">get_observable_event_deactivate_confirmation</a> when the change has been<br>
   * confirmed by the remote device.
   */
  public void deactivate() {
    AspenJNI.ISpatializerCapability_deactivate(swigCPtr, this);
  }

  /**
   * Set the spatializer mode<br>
   * <br>
   * @param mode The spatializer mode to set.
   */
  public void setMode(SpatializerMode mode) {
    AspenJNI.ISpatializerCapability_setMode(swigCPtr, this, mode.swigValue());
  }

  /**
   * Check if the spatializer is activated.<br>
   * <br>
   * @return True if it is activated, false if it is deactivated.
   */
  public boolean isActivated() {
    return AspenJNI.ISpatializerCapability_isActivated(swigCPtr, this);
  }

  /**
   * Check if the capability is in sync with the audio device.<br>
   * <br>
   * @return True if it is in sync, false if not in sync.
   */
  public boolean remoteDeviceInSync() {
    return AspenJNI.ISpatializerCapability_remoteDeviceInSync(swigCPtr, this);
  }

  /**
   * Get the configuration object<br>
   * <br>
   * @return The spatializer mode
   */
  public SpatializerMode getMode() {
    return SpatializerMode.swigToEnum(AspenJNI.ISpatializerCapability_getMode(swigCPtr, this));
  }

  /**
   * Check if the spatializer mode is supported<br>
   * <br>
   * @param mode The spatializer mode to check whether it is supported or not.<br>
   * <br>
   * @return Returns a boolean specifying whether the mode is supported or not.
   */
  public boolean isModeSupported(SpatializerMode mode) {
    return AspenJNI.ISpatializerCapability_isModeSupported(swigCPtr, this, mode.swigValue());
  }

  /**
   *  Notification that the capability is in sync with device<br>
   * <br>
   * On session establish the spatializer capability will synchronize with the remote<br>
   * device. On completion the observers will be notified with this event. The subject<br>
   * parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSyncComplete() {
    return AspenJNI.ISpatializerCapability_getObservableEventSyncComplete();
  }

  /**
   *  Confirmation from device that the spatializer is activated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#activate">activate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventActivateConfirmation() {
    return AspenJNI.ISpatializerCapability_getObservableEventActivateConfirmation();
  }

  /**
   *  Confirmation from device that the spatializer is deactivated<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#deactivate">deactivate</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDeactivateConfirmation() {
    return AspenJNI.ISpatializerCapability_getObservableEventDeactivateConfirmation();
  }

  /**
   *  Confirmation from device that the spatializer mode was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_mode">set_mode</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetConfirmation() {
    return AspenJNI.ISpatializerCapability_getObservableEventSetConfirmation();
  }

}
