/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The VirtualDeviceService<br>
 * <br>
 * This class is the VirtualDeviceService, providing access to capabilities that<br>
 * can be interacted with on an virtual audio device. A virtual audio device is<br>
 * an abstract audio device running within Aspen which can control audio features<br>
 * implemented in an audio system running on the same device.
 */
public class IVirtualDeviceService extends IDeviceService {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IVirtualDeviceService(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IVirtualDeviceService_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVirtualDeviceService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IVirtualDeviceService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Fills an audio stream buffer used with tone generator<br>
   * <br>
   * When a virtual device service is used and a hearing test is started, the<br>
   * VirtualDeviceService function,<br>
   * <a href="#IVirtualDeviceServiceCallbacks::start_tone_generator_audio_stream">IVirtualDeviceServiceCallbacks::start_tone_generator_audio_stream</a> is<br>
   * called. The Aspen client shall then create an audio stream and call<br>
   * fill_tone_generator_audio_stream_buffer when new samples are to be written<br>
   * to the audio player.<br>
   * <br>
   * @param buffer The audio buffer to fill
   */
  public void fillToneGeneratorAudioStreamBuffer(IntVector buffer) {
    AspenJNI.IVirtualDeviceService_fillToneGeneratorAudioStreamBuffer(swigCPtr, this, IntVector.getCPtr(buffer), buffer);
  }

}
