/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public abstract class IVirtualDeviceServiceCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IVirtualDeviceServiceCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVirtualDeviceServiceCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IVirtualDeviceServiceCallbacks obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_IVirtualDeviceServiceCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AspenJNI.IVirtualDeviceServiceCallbacks_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AspenJNI.IVirtualDeviceServiceCallbacks_change_ownership(this, swigCPtr, true);
  }

  /**
   * Callback function called when Aspen wants to store persistent data<br>
   * <br>
   * Called when using the VirtualDeviceService and the virtual device wants to<br>
   * store data persistently on a file system. The file name must contain the<br>
   * provided parameter id so it's possible to retrieve it when the function<br>
   * load_persistent_data is called.<br>
   * <br>
   * @param id The file id<br>
   * @param buffer A byte vector containing the data to be stored
   */
  public abstract void storePersistentData(int id, Uint8Vector buffer) ;

  /**
   * Callback function called when Aspen wants to load persistent data<br>
   * <br>
   * Called when using the VirtualDeviceService and the virtual device wants to<br>
   * load data from a file. The id must be retrieved from the stored file name.<br>
   * <br>
   * @param id The file id<br>
   * @param max_len The maximum number of bytes to be read. It may be fewer.<br>
   *                If more, return empty vector.<br>
   * @return A byte vector with the loaded data
   */
  public abstract Uint8Vector loadPersistentData(int id, long max_len) ;

  /**
   * Callback function called when Aspen wants to start an audio stream<br>
   * <br>
   * Called when using the VirtualDeviceService and the virtual device wants to<br>
   * start an audio stream to be used for the tone generator.<br>
   * <br>
   * @param sample_rate The sample rate in Hz
   */
  public abstract void startToneGeneratorAudioStream(int sample_rate) ;

  /**
   * Callback function called when Aspen wants to stop an audio stream<br>
   * <br>
   * Called when using the VirtualDeviceService and the virtual device wants to<br>
   * stop an audio stream used for the tone generator.
   */
  public abstract void stopToneGeneratorAudioStream() ;

  public IVirtualDeviceServiceCallbacks() {
    this(AspenJNI.new_IVirtualDeviceServiceCallbacks(), true);
    AspenJNI.IVirtualDeviceServiceCallbacks_director_connect(this, swigCPtr, true, true);
  }

}
