/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * The volume capability
 */
public class IVolumeCapability extends IObservableProperty {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IVolumeCapability(long cPtr, boolean cMemoryOwn) {
    super(AspenJNI.IVolumeCapability_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVolumeCapability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AspenJNI.delete_IVolumeCapability(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Set the volume limit<br>
   * <br>
   * If the volume limit is set higher than the maximum of the device,<br>
   * the request will go through and the volume limit will be set to the max.<br>
   * <br>
   * An asynchronous request to set the volume limit value.<br>
   * Observers will be notified with event <a href="#get_observable_event_set_volume_limit_confirmation">get_observable_event_set_volume_limit_confirmation</a><br>
   * when the change has been confirmed by the remote device.<br>
   * <br>
   * @param value The volume limit in dBSPL as an uint8_t.
   */
  public void setVolumeLimit(short value) {
    AspenJNI.IVolumeCapability_setVolumeLimit(swigCPtr, this, value);
  }

  /**
   * Get the volume limit<br>
   * <br>
   * @return uint8_t Returns the currently set volume limit in dBSPL.
   */
  public short getVolumeLimit() {
    return AspenJNI.IVolumeCapability_getVolumeLimit(swigCPtr, this);
  }

  /**
   * Get the maximum volume limit for the audio device<br>
   * <br>
   * The volume limit has been measured according to the standard<br>
   * BS EN 50332-1.<br>
   * <br>
   * @return The maximum volume limit as an uint8_t.
   */
  public short getMaximumVolumeLimit() {
    return AspenJNI.IVolumeCapability_getMaximumVolumeLimit(swigCPtr, this);
  }

  /**
   * Enable volume limit<br>
   * <br>
   * An asynchronous request to enable volume limit. Observers will be<br>
   * notified with event <a href="#get_observable_event_enable_volume_limit_confirmation">get_observable_event_enable_volume_limit_confirmation</a> when the change<br>
   * has been confirmed by the remote device.
   */
  public void enableVolumeLimit() {
    AspenJNI.IVolumeCapability_enableVolumeLimit(swigCPtr, this);
  }

  /**
   * Disable volume limit<br>
   * <br>
   * An asynchronous request to disable volume limit. Observers will be<br>
   * notified with event <a href="#get_observable_event_disable_volume_limit_confirmation">get_observable_event_disable_volume_limit_confirmation</a> when the change<br>
   * has been confirmed by the remote device.
   */
  public void disableVolumeLimit() {
    AspenJNI.IVolumeCapability_disableVolumeLimit(swigCPtr, this);
  }

  /**
   * Check if volume limit is enabled<br>
   * <br>
   * @return bool Returns true if volume limit is active, false if not.
   */
  public boolean isVolumeLimitEnabled() {
    return AspenJNI.IVolumeCapability_isVolumeLimitEnabled(swigCPtr, this);
  }

  /**
   * Check if the capability is in sync with the audio device.<br>
   * <br>
   * @return True if it is in sync, false if not in sync.
   */
  public boolean remoteDeviceInSync() {
    return AspenJNI.IVolumeCapability_remoteDeviceInSync(swigCPtr, this);
  }

  /**
   *  Notification that the capability is in sync with device<br>
   * <br>
   * On session establish the volume capability will synchronize with the remote<br>
   * device. On completion the observers will be notified with this event. The subject<br>
   * parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventGetVolumeLimitStatusConfirmation() {
    return AspenJNI.IVolumeCapability_getObservableEventGetVolumeLimitStatusConfirmation();
  }

  /**
   *  Confirmation from device that the volume limit is enabled<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed an<br>
   * <a href="#enable_volume_limit">enable_volume_limit</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventEnableVolumeLimitConfirmation() {
    return AspenJNI.IVolumeCapability_getObservableEventEnableVolumeLimitConfirmation();
  }

  /**
   *  Confirmation from device that the volume limit is disabled<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#disable_volume_limit">disable_volume_limit</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventDisableVolumeLimitConfirmation() {
    return AspenJNI.IVolumeCapability_getObservableEventDisableVolumeLimitConfirmation();
  }

  /**
   *  Confirmation from device that the volume limit was set<br>
   * <br>
   * Observers will be notified with this event when the remote device has confirmed a<br>
   * <a href="#set_volume_limit">set_volume_limit</a> request. The subject parameter is not used for this event.<br>
   * <br>
   * @return A string that identifies the event.
   */
  public static String getObservableEventSetVolumeLimitConfirmation() {
    return AspenJNI.IVolumeCapability_getObservableEventSetVolumeLimitConfirmation();
  }

}
