/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class ProfileGraph {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileGraph(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileGraph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ProfileGraph obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ProfileGraph(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ProfileGraph(FloatVector left, FloatVector right, UintVector frequencies) {
    this(AspenJNI.new_ProfileGraph(FloatVector.getCPtr(left), left, FloatVector.getCPtr(right), right, UintVector.getCPtr(frequencies), frequencies), true);
  }

  public FloatVector getLeft() {
    return new FloatVector(AspenJNI.ProfileGraph_getLeft(swigCPtr, this), true);
  }

  public FloatVector getRight() {
    return new FloatVector(AspenJNI.ProfileGraph_getRight(swigCPtr, this), true);
  }

  public UintVector getFrequencies() {
    return new UintVector(AspenJNI.ProfileGraph_getFrequencies(swigCPtr, this), true);
  }

}
