/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public class ProfileDataList extends java.util.AbstractSequentialList<ProfileData> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileDataList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileDataList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ProfileDataList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ProfileDataList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ProfileDataList(java.util.Collection c) {
    this();
    java.util.ListIterator<ProfileData> it = listIterator(0);
    // Special case the "copy constructor" here to avoid lots of cross-language calls
    for (java.lang.Object o : c) {
      it.add((ProfileData)o);
    }
  }

  public int size() {
    return doSize();
  }

  public boolean add(ProfileData value) {
    addLast(value);
    return true;
  }

  public java.util.ListIterator<ProfileData> listIterator(int index) {
    return new java.util.ListIterator<ProfileData>() {
      private Iterator pos;
      private Iterator last;

      private java.util.ListIterator<ProfileData> init(int index) {
        if (index < 0 || index > ProfileDataList.this.size())
          throw new IndexOutOfBoundsException("Index: " + index);
        pos = ProfileDataList.this.begin();
	pos = pos.advance_unchecked(index);
        return this;
      }

      public void add(ProfileData v) {
        // Technically we can invalidate last here, but this makes more sense
        last = ProfileDataList.this.insert(pos, v);
      }

      public void set(ProfileData v) {
        if (null == last) {
          throw new IllegalStateException();
        }
        last.set_unchecked(v);
      }

      public void remove() {
        if (null == last) {
          throw new IllegalStateException();
        }
        ProfileDataList.this.remove(last);
        last = null;
      }

      public int previousIndex() {
        return ProfileDataList.this.doPreviousIndex(pos);
      }

      public int nextIndex() {
        return ProfileDataList.this.doNextIndex(pos);
      }

      public ProfileData previous() {
        if (previousIndex() < 0) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.previous_unchecked();
        return last.deref_unchecked();
      }

      public ProfileData next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.next_unchecked();
        return last.deref_unchecked();
      }

      public boolean hasPrevious() {
        // This call to previousIndex() will be much slower than the hasNext() implementation, but it's simpler like this with C++ forward iterators
        return previousIndex() != -1;
      }

      public boolean hasNext() {
        return ProfileDataList.this.doHasNext(pos);
      }
    }.init(index);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AspenJNI.delete_ProfileDataList_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void set_unchecked(ProfileData v) {
      AspenJNI.ProfileDataList_Iterator_set_unchecked(swigCPtr, this, ProfileData.getCPtr(v), v);
    }
  
    public ProfileDataList.Iterator next_unchecked() {
      return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_Iterator_next_unchecked(swigCPtr, this), true);
    }
  
    public ProfileDataList.Iterator previous_unchecked() {
      return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_Iterator_previous_unchecked(swigCPtr, this), true);
    }
  
    public ProfileData deref_unchecked() {
      return new ProfileData(AspenJNI.ProfileDataList_Iterator_deref_unchecked(swigCPtr, this), true);
    }
  
    public ProfileDataList.Iterator advance_unchecked(int index) {
      return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_Iterator_advance_unchecked(swigCPtr, this, index), true);
    }
  
  }

  public ProfileDataList() {
    this(AspenJNI.new_ProfileDataList__SWIG_0(), true);
  }

  public ProfileDataList(ProfileDataList other) {
    this(AspenJNI.new_ProfileDataList__SWIG_1(ProfileDataList.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AspenJNI.ProfileDataList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AspenJNI.ProfileDataList_clear(swigCPtr, this);
  }

  public ProfileDataList.Iterator remove(ProfileDataList.Iterator pos) {
    return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_remove(swigCPtr, this, ProfileDataList.Iterator.getCPtr(pos), pos), true);
  }

  public void removeLast() {
    AspenJNI.ProfileDataList_removeLast(swigCPtr, this);
  }

  public void removeFirst() {
    AspenJNI.ProfileDataList_removeFirst(swigCPtr, this);
  }

  public void addLast(ProfileData value) {
    AspenJNI.ProfileDataList_addLast(swigCPtr, this, ProfileData.getCPtr(value), value);
  }

  public void addFirst(ProfileData value) {
    AspenJNI.ProfileDataList_addFirst(swigCPtr, this, ProfileData.getCPtr(value), value);
  }

  private ProfileDataList.Iterator begin() {
    return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_begin(swigCPtr, this), true);
  }

  public ProfileDataList.Iterator end() {
    return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_end(swigCPtr, this), true);
  }

  private ProfileDataList.Iterator insert(ProfileDataList.Iterator pos, ProfileData value) {
    return new ProfileDataList.Iterator(AspenJNI.ProfileDataList_insert(swigCPtr, this, ProfileDataList.Iterator.getCPtr(pos), pos, ProfileData.getCPtr(value), value), true);
  }

  public ProfileDataList(int count, ProfileData value) {
    this(AspenJNI.new_ProfileDataList__SWIG_2(count, ProfileData.getCPtr(value), value), true);
  }

  private int doSize() {
    return AspenJNI.ProfileDataList_doSize(swigCPtr, this);
  }

  private int doPreviousIndex(ProfileDataList.Iterator pos) {
    return AspenJNI.ProfileDataList_doPreviousIndex(swigCPtr, this, ProfileDataList.Iterator.getCPtr(pos), pos);
  }

  private int doNextIndex(ProfileDataList.Iterator pos) {
    return AspenJNI.ProfileDataList_doNextIndex(swigCPtr, this, ProfileDataList.Iterator.getCPtr(pos), pos);
  }

  private boolean doHasNext(ProfileDataList.Iterator pos) {
    return AspenJNI.ProfileDataList_doHasNext(swigCPtr, this, ProfileDataList.Iterator.getCPtr(pos), pos);
  }

}
