/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Class representing the meta data of a profile<br>
 * <br>
 * A profile is a calibration result along with some meta data, this class only represent the meta data and a graph<br>
 * of the calibration result.
 */
public class ProfileData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ProfileData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AspenJNI.delete_ProfileData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ProfileData(String name, String id, Gender gender, long created_timestamp, ProfileGraph graph, long last_used_timestamp, Audiogram audiogram) {
    this(AspenJNI.new_ProfileData(name, id, gender.swigValue(), created_timestamp, ProfileGraph.getCPtr(graph), graph, last_used_timestamp, Audiogram.getCPtr(audiogram), audiogram), true);
  }

  /**
   *  Get the name of a profile<br>
   * <br>
   * This method can be used to get the name of a profile.<br>
   * <br>
   * @return A string representing the name of a profile
   */
  public String getName() {
    return AspenJNI.ProfileData_getName(swigCPtr, this);
  }

  /**
   *  Get the profile id<br>
   * <br>
   * This method can be used to get the ID of a profile.<br>
   * <br>
   * @return A string representing the id of a profile.
   */
  public String getId() {
    return AspenJNI.ProfileData_getId(swigCPtr, this);
  }

  /**
   *  Get the gender of a profile<br>
   * <br>
   * This method can be used to get the gender of a profile.<br>
   * <br>
   * @return A gender representing the gender of a profile
   */
  public Gender getGender() {
    return Gender.swigToEnum(AspenJNI.ProfileData_getGender(swigCPtr, this));
  }

  /**
   *  Get the profile created timestamp<br>
   * <br>
   * This method can be used to get the creation time of the profile in epoch ms.<br>
   * <br>
   * @return An int64_t representing the created timestamp of a profile
   */
  public long getCreatedTimestamp() {
    return AspenJNI.ProfileData_getCreatedTimestamp(swigCPtr, this);
  }

  /**
   *  Get the profile graph<br>
   * <br>
   * This method can be used to get the hearing profile graph of a profile.<br>
   * <br>
   * @return A pointer to the hearing profile graph of a profile.
   */
  public ProfileGraph getProfileGraph() {
    return new ProfileGraph(AspenJNI.ProfileData_getProfileGraph(swigCPtr, this), false);
  }

  /**
   *  Equality check for the profile ID<br>
   * <br>
   * This method checks whether the profile's ID is identical to another profile's ID.<br>
   * <br>
   * @param other A profile object to check equality against<br>
   * @return True if the profile IDs are equal, false if they are not.
   */
  public boolean idEquals(ProfileData other) {
    return AspenJNI.ProfileData_idEquals(swigCPtr, this, ProfileData.getCPtr(other), other);
  }

  /**
   * Get the last used timestamp<br>
   * <br>
   * This method can be used to get the last used timestamp of the profile in epoch ms.<br>
   * <br>
   * @return An int64_t representing the last used timestamp of a profile.
   */
  public long getLastUsedTimestamp() {
    return AspenJNI.ProfileData_getLastUsedTimestamp(swigCPtr, this);
  }

  /**
   * Get the audiogram<br>
   * <br>
   * This method can be used to get the audiogram of the profile.<br>
   * <br>
   * @return const Audiogram The audiogram of the profile.
   */
  public Audiogram getAudiogram() {
    return new Audiogram(AspenJNI.ProfileData_getAudiogram(swigCPtr, this), true);
  }

}
