/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum RoomId {
  ID_0,
  ID_1,
  ID_2,
  ID_3;

  public final int swigValue() {
    return swigValue;
  }

  public static RoomId swigToEnum(int swigValue) {
    RoomId[] swigValues = RoomId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (RoomId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + RoomId.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private RoomId() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private RoomId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private RoomId(RoomId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

