/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

/**
 * Spatializer modes
 */
public enum SpatializerMode {
  SPATIALIZER_MODE_SUBTLE,
  SPATIALIZER_MODE_ROOM,
  SPATIALIZER_MODE_SUBTLE_PLUS,
  SPATIALIZER_MODE_ROOM_PLUS;

  public final int swigValue() {
    return swigValue;
  }

  public static SpatializerMode swigToEnum(int swigValue) {
    SpatializerMode[] swigValues = SpatializerMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SpatializerMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SpatializerMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SpatializerMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SpatializerMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SpatializerMode(SpatializerMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

