/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum SpeakerPosition {
  FRONT_LEFT,
  FRONT_RIGHT,
  REAR_LEFT,
  REAR_RIGHT;

  public final int swigValue() {
    return swigValue;
  }

  public static SpeakerPosition swigToEnum(int swigValue) {
    SpeakerPosition[] swigValues = SpeakerPosition.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SpeakerPosition swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SpeakerPosition.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SpeakerPosition() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SpeakerPosition(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SpeakerPosition(SpeakerPosition swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

