/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audiodo.aspen;

public enum SpeakerConstellation {
  FRONT_ONLY,
  FRONT_AND_REAR;

  public final int swigValue() {
    return swigValue;
  }

  public static SpeakerConstellation swigToEnum(int swigValue) {
    SpeakerConstellation[] swigValues = SpeakerConstellation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SpeakerConstellation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SpeakerConstellation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SpeakerConstellation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SpeakerConstellation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SpeakerConstellation(SpeakerConstellation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

